var FAQ = Array({category:"About deviantART", catpath:"deviantart/aboutdeviantart"},
{id:29,question:"How do I become a Senior Member?"},
{id:106,question:"What are the symbol next to each deviant's username?"},
{id:116,question:"What is deviantART and who founded deviantART?"},
{id:546,question:"Is deviantART free?"},
{category:"About Points", catpath:"points/aboutpoints"},
{id:234,question:"What are Points?"},
{id:235,question:"Where can I find my Points balance?"},
{id:279,question:"How do I earn Points?"},
{id:894,question:"Can I run a lottery for Points on deviantART?"},
{id:895,question:"Can I offer an automated service on deviantART in exchange for deviantPOINTS?"},
{category:"About Prints", catpath:"printsservice/aboutprints"},
{id:177,question:"Does my print account ever expire?"},
{id:179,question:"What is deviantART Prints?"},
{id:210,question:"What technology does the deviantART Prints Service use?"},
{id:338,question:"What are the rules for selling prints?"},
{category:"Policies: Abuses & Exploits", catpath:"deviantart/policies/abusesandexploits"},
{id:54,question:"What is 'flooding'?"},
{id:263,question:"What is 'spamming'?"},
{id:295,question:"What exactly is an 'Abuse or Exploit of the System'?"},
{id:574,question:"Can I advertise on deviantART without purchasing an official advertising package?"},
{category:"Problems & Errors: Account Creation Issues", catpath:"deviantart/problemserrors/accountcreationissues"},
{id:40,question:"I tried to create an account but the email address I tried to use was blocked; why?"},
{id:568,question:"I tried to create an account, but it states my IP Address is banned and will not let me continue. Why?"},
{id:649,question:"I have yet to receive my Verify email. What can I do?"},
{id:650,question:"I have Verified my email repeatedly and it still reports I need to verify it. What can I do?"},
{category:"Policies: Bans & Suspensions", catpath:"deviantart/policies/banssuspensions"},
{id:221,question:"I was banned, is there anything I can do?"},
{id:325,question:"Will you tell me why my friend was banned?"},
{id:610,question:"What happens when someone is banned or suspended?"},
{category:"Policies: Behavior & Interaction", catpath:"deviantart/policies/behaviorinteraction"},
{id:3,question:"Are there restrictions to comments?"},
{id:34,question:"Are there any rules for the journals?"},
{id:214,question:"What are deviantART's policies regarding avatars?"},
{id:303,question:"I'm offended by something I saw on the website!"},
{id:911,question:"How do I report a Note which I received as spam or as abuse?"},
{category:"Beta Testing", catpath:"premiummembership/betatesting"},
{id:531,question:"What is an Official deviantART Beta Tester? How do I become one?"},
{id:532,question:"As an Official Beta Tester, how do I provide feedback?"},
{id:541,question:"If I'm a beta tester, may I choose to opt-out of the program later?"},
{category:"Browsing & Comments: Browsing", catpath:"deviantart/browsingcomments/browsing"},
{id:44,question:"I am a mobile interface user, but I do not wish to use this interface. How can I disable it?"},
{id:45,question:"What are Channels and how do I use them?"},
{id:125,question:"What is SitBack and how do I use SitBack?"},
{id:333,question:"What does it mean when a user's page says 'is currently idle' or 'last visited'?"},
{id:608,question:"Can I browse a user's gallery by a specific Category?"},
{id:642,question:"How do I use the Browse interface?"},
{category:"Buying Prints", catpath:"printsservice/buyingprints"},
{id:173,question:"What if my order is damaged when I receive it?"},
{id:175,question:"Is there tax on prints?"},
{id:181,question:"Can I still buy prints if I don't have a credit card?"},
{id:188,question:"Can I buy a frame with my prints?"},
{id:194,question:"Can I buy prints for someone outside my country?"},
{id:195,question:"Do I have to buy a frame to get my print?"},
{id:198,question:"Is there a discount on bulk orders?"},
{id:619,question:"Is there a time limit regarding reporting unsatisfactory orders?"},
{id:738,question:"Can I place an order or speak to a representative over the phone?"},
{id:771,question:"Where can I check my order status and details?"},
{id:884,question:"How do I login to or signup for a buyer account?"},
{id:893,question:"Who processes and ships the prints orders?"},
{category:"Campaign Questions", catpath:"adcast/campaignquestions"},
{id:600,question:"How do I know how successful my campaign was?"},
{id:780,question:"What kind of file types can I submit for my AdCast campaign?"},
{id:782,question:"How long will it take for my campaign to start?"},
{id:888,question:"Why don't my site pageviews match the number of clicks my campaign report says I received?"},
{category:"Chat Network & Forums: Chatroom Customization", catpath:"deviantart/chatnetworkforums/chatroomcustomization"},
{id:17,question:"I just created my chatroom and I’m confused.  Are there any tutorials?"},
{id:291,question:"Can I change the description of my chatroom?"},
{id:507,question:"How do I make a private room?"},
{id:510,question:"What is a bot, and how can I get one?"},
{id:513,question:"How do I change the title (or topic) on the top of my chatroom?"},
{id:540,question:"How can I customize my chatroom?"},
{category:"Problems & Errors: Comment Issues", catpath:"deviantart/problemserrors/commentissues"},
{id:31,question:"I am unable to post comments or send notes because the site informed me I was spamming. What is going on?"},
{id:351,question:"What does it mean if I receive or see a comment from 'Nobody'?"},
{category:"Browsing & Comments: Comments", catpath:"deviantart/browsingcomments/comments"},
{id:14,question:"How do I create a link to a specific comment?"},
{id:41,question:"What do the 'Parent', 'Top' and 'Reply' links under comments mean?"},
{id:160,question:"Can I remove or delete comments on my userpage, journal or deviations?"},
{id:661,question:"How do I post a comment?"},
{category:"Commissions", catpath:"premiumcontentplatform/commissions"},
{id:370,question:"What are Commissions?"},
{id:371,question:"When do I have to pay for a commission?"},
{id:372,question:"When do I get paid for my Commission?"},
{id:373,question:"What happens if an artist doesn't deliver a Commission?"},
{id:374,question:"How do I settle a Commission dispute?"},
{id:375,question:"I requested a Commission, but the artist still hasn't accepted or rejected it, what can I do?"},
{id:899,question:"Why can't I use credit cards or PayPal on Premium Content Platform and Commissions purchases?"},
{id:904,question:"How do I get to the Commissions shop?"},
{category:"Content Questions", catpath:"adcast/contentquestions"},
{id:594,question:"What size should my advertisement be?"},
{id:595,question:"When you say 'Anything having to do with a corporation or commercial content of any kind'; does that mean I cannot link my advertisements to my website where I can make money off my art?"},
{id:596,question:"Can I advertise for my erotic art site?"},
{id:597,question:"Can I submit an advertisement which contains nudity or erotic content?"},
{id:744,question:"What should my advertisement look like?"},
{id:779,question:"Can I submit a different sized banner other than 300x250 for my AdCast campaign?"},
{category:"Problems & Errors: Cookies & Cache", catpath:"deviantart/problemserrors/cookiescache"},
{id:643,question:"I was asked to clear my browser's cache. How do I do this?"},
{id:644,question:"I was told to make sure my cookies are properly enabled. How do I do this?"},
{id:645,question:"I was told I should try deleting my cookies. How do I do this?"},
{category:"Policies: Copyright Concerns", catpath:"deviantart/policies/copyrightconcerns"},
{id:8,question:"What are violations of the deviantART copyright policy?"},
{id:32,question:"Fair Use and Your Submission"},
{id:63,question:"What sort of things can I use for Preview images?"},
{id:501,question:"What are 'warez', 'cracks' and 'keygens'? Do you allow those?"},
{id:614,question:"What can I use for music tracks and sound effects in my animation or film?"},
{id:814,question:"Should I put a signature, watermark or copyright notice on my art before submitting it?"},
{category:"Copyrights", catpath:"printsservice/copyrights"},
{id:743,question:"Can I sell fan art as prints?"},
{id:751,question:"Is permission needed when using collaborative artwork for commercial sales?"},
{id:752,question:"If my print contains an image that isn't mine, can I still use it for print?"},
{id:792,question:"As a stock art resource provider, how can I be of help in regards of stock art resource usage in prints?"},
{id:828,question:"Can I sell vintage artwork in my deviantART Print Store?"},
{category:"Critique Feature", catpath:"premiummembership/critiquefeature"},
{id:95,question:"What is the Critique Feature and how do I use it?"},
{category:"Deviations & Scraps: Daily Deviation", catpath:"deviantart/deviationsscraps/dailydeviation"},
{id:18,question:"Who selects Daily Deviations and how are they chosen?"},
{id:61,question:"What is a Daily Deviation?"},
{id:313,question:"How can I find out if someone already has a Daily Deviation?"},
{id:873,question:"What do I do when I disapprove of a Daily Deviation feature?"},
{category:"deviantART T-shirts & Gear Design Battle", catpath:"deviantarttshirtsgear/deviantarttshirtsgeardesignbattle"},
{id:270,question:"How do I vote in a deviantART contest or design challenge?"},
{id:271,question:"Can I cancel a vote?"},
{id:272,question:"Why I am having trouble voting?"},
{id:273,question:"Do I still own rights to my image after submitting the image to a deviantART contest?"},
{id:274,question:"How often can I vote in a deviantART contest or challenge that uses the voting platform?"},
{id:275,question:"How does deviantART prevent users from cheating during the voting for its contests?"},
{category:"My Account: deviantWATCH", catpath:"deviantart/myaccount/deviantwatch"},
{id:19,question:"If I remove someone from my deviantWATCH, will they be notified?"},
{id:26,question:"What is the deviantWATCH and how do I manage my deviantWATCH listing?"},
{id:68,question:"Can I remove someone who is watching me?"},
{category:"Problems & Errors: Display Issues", catpath:"deviantart/problemserrors/displayissues"},
{id:75,question:"Many images will not load for me or all I see is red x's. Why?"},
{id:638,question:"Sometimes deviantART loads funny in my browser. What causes this?"},
{id:647,question:"I'm a Firefox user and images have stopped loading in my browser. How can I fix this?"},
{id:664,question:"My friends username has a dash before, after it or both and I cannot access their page. Why is this?"},
{id:672,question:"I can no longer see animations such as avatars and emoticons play on deviantART and possibly elsewhere. What could be causing this?"},
{category:"Deviations & Scraps: Downloading", catpath:"deviantart/deviationsscraps/downloading"},
{id:64,question:"How do I download Tutorials?"},
{id:602,question:"How do I download Brushes?"},
{category:"My Account: Edit Settings & Profile", catpath:"deviantart/myaccount/editsettingsprofile"},
{id:4,question:"Which options can I control under the Edit Settings page?"},
{id:93,question:"How does the Mature Content option work?"},
{id:147,question:"How do I upload or remove an avatar for my profile?"},
{id:912,question:"How do Mature Content settings work in the DeviantArt Mobile App?"},
{category:"Help Desk & FAQ: FAQ", catpath:"deviantart/helpdeskfaq/faq"},
{id:158,question:"I think something is missing from the FAQ."},
{id:606,question:"I found an error in the FAQ. Where can I report this?"},
{category:"Deviations & Scraps: Favourites", catpath:"deviantart/deviationsscraps/favourites"},
{id:11,question:"Is there a way to see which deviants have added my deviation submission to their favourites?"},
{id:59,question:"How do I add and delete Favourites?"},
{category:"File Formats", catpath:"printsservice/fileformats"},
{id:136,question:"Should I submit print images as RGB or CMYK?"},
{id:137,question:"What are the advantages/disadvantages of each image file format?"},
{id:138,question:"What file types are accepted by Prints?"},
{id:176,question:"What are JPEG, PNG, and BMP files?"},
{category:"Problems & Errors: Firewall Issues", catpath:"deviantart/problemserrors/firewallissues"},
{id:653,question:"My Firewall reported that deviantART is trying to attack me. Why is this happening?"},
{category:"Deviations & Scraps: Gallery Management", catpath:"deviantart/deviationsscraps/gallerymanagement"},
{id:199,question:"How do I add Mature Content tag to my deviation?"},
{id:299,question:"What are my Personal Gallery Management Tools, and how do I get to them?"},
{id:307,question:"What is the Deviation Storage Tool, and how do I access it? Can I temporarily hide deviations?"},
{id:554,question:"Is my deviation Mature Content?"},
{category:"General", catpath:"printsservice/general"},
{id:135,question:"What is the print quality like?"},
{id:183,question:"What is a glossy finish?"},
{id:184,question:"What is a matte finish?"},
{id:185,question:"Which is better, Glossy, Matte or <i>Lustre</i>® finishes?"},
{id:222,question:"Why is my print preview so small?"},
{id:230,question:"How do I purchase items for someone from their wishlist?"},
{id:280,question:"What is a <i>Lustre</i>® finish?"},
{id:281,question:"What are the products offered by the deviantART Prints service?"},
{id:551,question:"When will the Calendar year change over for any Calendars I have submitted?"},
{id:603,question:"How would a photograph look printed on canvas?"},
{id:604,question:"What are Wrapped Canvas prints mounted on?"},
{id:605,question:"How can I tell who added my print to their wishlist?"},
{id:775,question:"Can more than one person use a Print Account?"},
{id:794,question:"How will the artwork be displayed on coffee mugs?"},
{id:808,question:"What do the products offered by the deviantART Prints Service look like?"},
{id:876,question:"How do I use the Shop Search?"},
{id:879,question:"What is the Wishlist and how do I manage my Wishlist?"},
{id:885,question:"What is the difference between Wrapped Canvas and Rolled Canvas?"},
{category:"Deviations & Scraps: General", catpath:"deviantart/deviationsscraps/general"},
{id:10,question:"Will the deviantART staff remove all my deviations for me because it takes too long for me to delete deviations one by one?"},
{id:15,question:"What is a deviation?"},
{id:70,question:"What is the format for the Keywords in deviations and what are they for?"},
{id:72,question:"How do I edit or delete my deviation or scrap submissions?"},
{id:163,question:"Where can I find the description to a Gallery that I want to submit to?"},
{id:211,question:"How do I get my camera's specifications to show or not show up when I submit a picture?"},
{id:332,question:"Does deviantART have a feature that will automatically watermark my deviations?"},
{id:552,question:"Is there a limit to how many deviations I can submit?"},
{id:666,question:"Will my watchers be notified of my deviation and scrap submission edits?"},
{id:753,question:"Are there any limitations for deviation submissions?"},
{id:872,question:"Does deviantART allow music submissions?"},
{category:"My Account: General", catpath:"deviantart/myaccount/general"},
{id:56,question:"How can I get noticed on this site?"},
{id:112,question:"How do I change my deviantART username?"},
{id:113,question:"Can I delete my deviantART account?"},
{id:201,question:"Do you close unused accounts, or release them to the public?"},
{id:662,question:"How do I create an Avatar, to display on my User Page and next to my Comments?"},
{id:673,question:"How can I make a club or group?"},
{id:745,question:"How can I send a note to another deviant?"},
{category:"Problems & Errors: General", catpath:"deviantart/problemserrors/general"},
{id:24,question:"I just tagged someones comment as spam by mistake, will anything happen to the user?"},
{id:57,question:"I see one of my issues listed in the Status Forum, but I do not see 'all' of my issues listed. What do I do?"},
{id:656,question:"My friend gave me their deviantART username, but I have no clue how to locate them. How do I do this?"},
{id:716,question:"I was told to make sure I have Javascript enabled. How do I do this?"},
{id:719,question:"I read in the 'Status Forum' that an issue was fixed but I think it's happening again. Why is this?"},
{id:722,question:"Why do certain bugs take longer than others to be fixed?"},
{id:723,question:"How come things are not better tested before they are released?"},
{id:724,question:"Why do you put out new features when things are broken?"},
{id:756,question:"I was told to update my browser. How do I do this?"},
{id:859,question:"I was asked by an administrator in the Help Desk to supply a link to my image, comment, forum thread, etc. How do I include a link in my reply?"},
{id:861,question:"How do I take a screenshot for my Help Desk ticket?"},
{category:"Chat Network & Forums: General", catpath:"deviantart/chatnetworkforums/general"},
{id:50,question:"Why do I receive 'posting restricted errors' when replying to a forum thread?"},
{id:51,question:"Why do my threads keep getting closed?"},
{id:58,question:"Where is the Shoutbox?"},
{id:288,question:"What does the Fella icon by a chatroom name mean?"},
{id:289,question:"How do I create or delete a chatroom?"},
{id:290,question:"How do I manage the users in my chatroom, and set operators and members?"},
{id:292,question:"What are the commands that I can use on the chat network?"},
{id:293,question:"Why am I having technical issues using the Chat Network?"},
{id:294,question:"What is dAmn?"},
{id:508,question:"How do I post the raw HTML or emoticon codes in chatrooms?"},
{id:511,question:"How do I post thumbnails of my art on the Chat Network or Forums?"},
{id:512,question:"How do I know where my friends are chatting?"},
{id:514,question:"Can I join more than one room in a single browser?"},
{id:618,question:"Does deviantART have a Forum system?"},
{id:709,question:"Can I close or delete my forum thread?"},
{id:874,question:"What is the purpose of the #help chatroom?"},
{category:"General deviantART T-shirts & Gear Questions", catpath:"deviantarttshirtsgear/generaldeviantarttshirtsgearquestions"},
{id:580,question:"What are the return and exchange policies for deviantART T-Shirts & Gear merchandise?"},
{id:583,question:"How long does it take to receive my deviantART T-Shirts & Gear order?"},
{id:900,question:"Why can’t I find a way to purchase deviantART Gear Items?"},
{id:901,question:"How long does it take to receive my deviantART T-Shirts & Gear order?"},
{id:902,question:"What happens if my order does not arrive or arrives damaged?"},
{category:"General Group Questions", catpath:"groups/generalgroupquestions"},
{id:400,question:"I created a group but users cannot join. How do I let them?"},
{id:401,question:"I’m experiencing problems with my group, what can I do?"},
{id:402,question:"I’m an admin in a group but cannot perform administrative actions, why?"},
{id:403,question:"How will others know that I’m part of a group? How do I know what groups I'm in?"},
{id:404,question:"How do I upload an avatar for my group and what are the limitations?"},
{id:405,question:"How do I leave a group I no longer wish to be a part of?"},
{id:406,question:"How do I remove a user’s deviation from my groups gallery/favs?"},
{id:407,question:"How do I remove my deviations from a group?"},
{id:408,question:"Can I delete my group?"},
{id:409,question:"As the founder can I appoint someone to replace me?"},
{id:410,question:"What are the official deviantART groups?"},
{id:411,question:"What’s the difference between a group administrator and a non-administrator?"},
{id:416,question:"How will I be notified when changes are made to my group?"},
{id:417,question:"How do Founders or other administrators promote, or demote, their members?"},
{id:422,question:"How many groups can I join?"},
{id:430,question:"Can any member of the group submit deviations to the group's gallery?"},
{id:431,question:"Can a group sell prints? If so, where do the profits go?"},
{id:432,question:"Where will my Groups activity go in my Message Centre?"},
{category:"General Premium Membership Questions", catpath:"premiummembership/generalpremiummembershipquestions"},
{id:28,question:"What are the benefits of becoming a Premium Member?"},
{id:148,question:"What methods of payment are accepted for purchasing deviantART Premium Membership Packages?"},
{id:228,question:"Can I transfer my deviantART Premium Membership?"},
{id:236,question:"Will my deviantART Premium Membership be auto renewed?"},
{id:253,question:"If I have a Premium Membership and purchase another, what happens to the existing Premium Membership?"},
{id:518,question:"Can I use another person's credit card to purchase a Premium Membership?"},
{id:749,question:"If I purchase a Premium Membership to deviantART will I receive an email confirming my purchase?"},
{id:824,question:"What is the difference between a Prepaid Premium Membership Package and a Billing one?"},
{id:825,question:"How do I cancel my rebilling Premium Membership?"},
{category:"General Questions", catpath:"adcast/generalquestions"},
{id:591,question:"Where will my advertisement show up and who will see it?"},
{id:592,question:"How long will my campaign run?"},
{id:593,question:"Can I buy both Homepage and Profile Page, or can I only buy one?"},
{id:598,question:"The last time I purchased an AdCast package, the advertisement size was different. Why?"},
{id:728,question:"There was a movie trailer takeover on the homepage.  What was that?"},
{id:729,question:"Why can’t I see my ad on the homepage?"},
{id:730,question:"What is 'frequency capping'?"},
{id:739,question:"What is AdCast?"},
{id:740,question:"Who will see my ad?"},
{id:746,question:"I have a question about AdCast not covered in the FAQ. Who can I contact for further information?"},
{id:747,question:"What is an 'impression'?"},
{id:757,question:"What other ads will I see on the deviantART Homepage?"},
{id:758,question:"Am I guaranteed a certain number of clicks on AdCast Homepage ads?"},
{id:777,question:"I want to buy an AdCast subscription for another person, either as a gift or a prize for a contest I am running. How can I do this?"},
{id:781,question:"I am not happy with my AdCast order. What are the AdCast refund policies?"},
{category:"General Questions", catpath:"orderingsupport/generalquestions"},
{id:27,question:"How do I locate my order history?"},
{id:52,question:"How do I purchase items for someone from their wishlist?"},
{id:631,question:"Is it safe to use my credit card at deviantART?"},
{id:731,question:"What is a CVV Code and where can I find mine?"},
{id:732,question:"What is Verified by Visa or SecureCode and why do I need to use it?"},
{id:774,question:"Can I place an order or speak to a representative over the phone?"},
{category:"General Questions", catpath:"deviantfilm/generalquestions"},
{id:831,question:"Why can't just anyone submit film?"},
{id:836,question:"How does the 'Film' invitation process work?"},
{id:847,question:"Does deviantART make films?"},
{id:848,question:"Does deviantART offer film distribution?"},
{id:852,question:"Where can I find music for my films?"},
{id:853,question:"How can I convert or compress my videos?"},
{id:855,question:"Is there a chat room for film?"},
{category:"About deviantART: General Use", catpath:"deviantart/aboutdeviantart/generaluse"},
{id:9,question:"What are the limits for Thumbnails and Emoticons?"},
{id:30,question:"How can we stay informed about new changes, updates, and technical problems with deviantART?"},
{id:38,question:"Which browsers and Mobile OS are supported by deviantART?"},
{id:46,question:"How do I use the Community Footer found on main deviantART pages?"},
{id:53,question:"How do I use Emoticons? Where are they?"},
{id:81,question:"How can I create links to other deviants, deviations, or websites?  <da:embed profile='youtube' id='eWM2joNb9NE' />"},
{id:104,question:"What HTML formatting can we use on deviantART? And what is the format for these codes?"},
{id:133,question:"Why does dA have US Only Contests?"},
{id:335,question:"What are RSS feeds and how do I use them?"},
{id:790,question:"Where can I download the Official deviantART Flash preloader?"},
{category:"Gift Premium Memberships", catpath:"premiummembership/giftpremiummemberships"},
{id:55,question:"I wish to purchase a Gift Premium Membership for another member, what should I know?"},
{category:"Guides", catpath:"deviantfilm/guides"},
{id:830,question:"How do I submit Film?"},
{category:"Help Desk & FAQ: Help Desk", catpath:"deviantart/helpdeskfaq/helpdesk"},
{id:215,question:"I have not received a response to my Help Desk Inquiry? What could be the reason or reasons for this?"},
{id:264,question:"Is there a description of the Help Desk contact categories?"},
{id:538,question:"I can't log in to use the Community Help Desk, is there an email?"},
{id:590,question:"What are the hours of operation for the Help Desk?"},
{id:630,question:"Are there any rules for the Help Desk?"},
{id:713,question:"Who is on the Help Desk Team?"},
{id:741,question:"How are Help Desk responses sent to me? Can I have them e-mailed to me?"},
{id:742,question:"I am unable to receive or see messages at this time in my 'Message Centre'. Does this also mean I cannot receive or see Help Desk responses?"},
{id:767,question:"Can I create a link to the Help Desk?"},
{category:"My Account: Journal", catpath:"deviantart/myaccount/journal"},
{id:62,question:"How do I use Journal skins?"},
{id:66,question:"What journal features do I have access to?"},
{id:67,question:"How do I share Journal Skins?"},
{id:69,question:"Can I use animated images within my journal, journal CSS or journal background?"},
{id:100,question:"How do I add, edit or delete journal entries?"},
{id:101,question:"How do I customize my journal page?"},
{id:197,question:"How many avatars am I allowed to post in my journal?"},
{id:892,question:"What is the file format for Journal skins?"},
{id:910,question:"Why don't some Journals display properly on my mobile phone?"},
{category:"Problems & Errors: Login Issues", catpath:"deviantart/problemserrors/loginissues"},
{id:115,question:"I entered my username and password correctly but am not able to login. Why?"},
{category:"Problems & Errors: Lost Password Issues", catpath:"deviantart/problemserrors/lostpasswordissues"},
{id:657,question:"I have yet to receive my Lost Password email. What can I do?"},
{id:658,question:"I received the confirmation code, but deviantART tells me it's invalid. What can I do?"},
{id:659,question:"I forgot my username or I have lost my password and forgot to update my email address on file. What can I do?"},
{category:"Make a Group", catpath:"groups/makeagroup"},
{id:418,question:"What are Groups and how do I make one?"},
{id:419,question:"Are Groups free?"},
{id:421,question:"How many groups can I make at one time?"},
{id:423,question:"Why is there a limit on how many groups I can be an administrator of?"},
{id:425,question:"What happens after I submit my application?"},
{id:428,question:"What happens when my Premium Membership expires and and I am an administrator of more than three (3) groups?"},
{id:429,question:"What is the 'Admin Area'?"},
{category:"Policies: Mature Content & Pornography", catpath:"deviantart/policies/maturecontentpornography"},
{id:13,question:"Does a Mature Content tag make it safe for me to submit whatever I want?"},
{id:251,question:"You prohibit the submission of 'pornographic literature'; what do you consider this to be?"},
{id:305,question:"Is posting 'Adult' oriented artwork alright if I censor it first?"},
{id:565,question:"You prohibit the submission of 'pornographic imagery'; what do you consider this to be?"},
{category:"Policies: Miscellaneous Policies", catpath:"deviantart/policies/miscellaneouspolicies"},
{id:73,question:"Are there any rules for Collection folder titles?"},
{id:302,question:"How does the staff decide to take action? Why does it seem inconsistent?"},
{id:502,question:"Can I submit things which I made using different 'games' like a doll maker or with other character generators?"},
{id:557,question:"Can I submit art which I have made using a 'base' (or line art) created by someone else?"},
{id:572,question:"What does deviantART consider 'Fan Art' to be?"},
{category:"My Account: My Earnings", catpath:"deviantart/myaccount/myearnings"},
{id:97,question:"How can I see how much money I've made?"},
{id:98,question:"Can I cancel a check after it has already been processed?"},
{id:99,question:"What should I do if I never received the check I requested from My Earnings?"},
{id:123,question:"When will I receive my earnings check?"},
{category:"My Account: My Favourites & Collections", catpath:"deviantart/myaccount/myfavouritescollections"},
{id:6,question:"What is the Collections Feature and how do I use it?"},
{id:244,question:"If I remove a favourite or collection, is the deviant notified of its removal?"},
{id:787,question:"Can I change the order of my Favourites or select what shows up in the Favourites section?"},
{category:"My Account: My Gallery", catpath:"deviantart/myaccount/mygallery"},
{id:560,question:"How do I add a Literature Author tag to appear with my literature deviations? How can I remove this tag later?"},
{id:762,question:"What is the Gallery Folders Feature and how do I use it?"},
{id:864,question:"How can I add or remove deviations from my Featured Gallery section."},
{id:867,question:"Is it possible to move deviations from one page to another in my gallery?"},
{category:"My Account: My Message Centre", catpath:"deviantart/myaccount/mymessagecentre"},
{id:1,question:"What is the Message Centre and how do I use it?"},
{id:37,question:"I deleted items in my Message Centre and they all came back, why is this?"},
{id:71,question:"How long do messages stay in my Message Centre?"},
{id:87,question:"Is there a limit on how many messages I can have?"},
{category:"My Account: My Profile Page", catpath:"deviantart/myaccount/myprofilepage"},
{id:90,question:"How do I customize my profile page?"},
{id:96,question:"Can I block people from interacting with me?"},
{id:569,question:"What is the 'Give' button on profile pages for?"},
{id:896,question:"People keep sending me llamas, what are they?"},
{id:897,question:"Can I turn off the ability to receive badges?"},
{category:"Policies: Nudity & Mature Content", catpath:"deviantart/policies/nuditymaturecontent"},
{id:23,question:"What are deviantART's policies on nudity?"},
{id:248,question:"Are there restrictions on art using children or teenagers (fictional or otherwise)?"},
{id:249,question:"Are there restrictions on photographs of teenagers or children?"},
{id:252,question:"Model release forms? Do I need it? What is it?"},
{category:"Policies: Ownership Issues", catpath:"deviantart/policies/ownershipissues"},
{id:5,question:"Can I use the deviantART emoticons on my website?"},
{id:94,question:"Can I use the works which I find on deviantART?"},
{id:226,question:"Does deviantART own my art?"},
{category:"Policies: Permission Issues", catpath:"deviantart/policies/permissionissues"},
{id:157,question:"Can I use things created by other people in my submissions?"},
{id:193,question:"How do I prove that I had permission to use someone's work?"},
{id:257,question:"What sort of permission do I need to use someone else's work?"},
{id:304,question:"Do you remove copies and trace-over art?"},
{id:306,question:"Does 'Crediting' let me use whatever I want?"},
{category:"Policies", catpath:"deviantart/policies"},
{id:2,question:"Where can I find the official deviantART Copyright Policy?"},
{id:20,question:"Where can I find the deviantART Terms of Service?"},
{id:33,question:"Where can I find the deviantART Submission Agreement?"},
{id:35,question:"Where is the Etiquette policy for deviantART?"},
{id:76,question:"Where can I find the deviantART Privacy Policy?"},
{id:220,question:"What is Mature Content?"},
{id:250,question:"The laws of my country differ from those of the United States- which ones apply?"},
{id:696,question:"How does deviantART comply with COPPA?"},
{category:"Policies", catpath:"deviantfilm/policies"},
{id:47,question:"My film has some copyrighted images in it, can I still post it?"},
{id:844,question:"Can I submit a film with copyrighted music?"},
{category:"Chat Network & Forums: Policy", catpath:"deviantart/chatnetworkforums/policy"},
{id:287,question:"What rules apply to the Chat Network?"},
{id:506,question:"Does deviantART allow sexual discussions in comments, chatrooms or the forums?"},
{id:558,question:"Am I allowed to put my bot in an Official channel?"},
{id:708,question:"I found a forum thread that I believe violates policies, where can I go to report it?"},
{id:795,question:"Am I allowed to own a bot on the chat network?"},
{id:801,question:"Are there any rules for the Forums?"},
{category:"Portfolio", catpath:"premiummembership/portfolio"},
{id:103,question:"Does my premium membership include a domain name for my portfolio?"},
{id:107,question:"GoDaddy"},
{id:108,question:"Register.com"},
{id:109,question:"Network Solutions"},
{id:110,question:"Enom"},
{category:"Premium Content Platform", catpath:"premiumcontentplatform/premiumcontentplatform"},
{id:360,question:"What is the Premium Content Platform?"},
{id:361,question:"How do I purchase Digital Files on the Premium Content Platform?"},
{id:362,question:"How do I sell Digital Files of art-related Content?"},
{id:363,question:"When do I get paid for my Digital Files of art-related content?"},
{id:364,question:"How do I settle a dispute?"},
{id:365,question:"May I Sell Stock on the Premium Content Platform?"},
{id:366,question:"Can I Sell Mature Content on the Premium Content Platform?"},
{id:903,question:"Why may I only purchase digital content with Points?"},
{id:909,question:"What does a 'PayPal verified email' mean?"},
{category:"Pricing and Payment", catpath:"printsservice/pricingandpayment"},
{id:120,question:"Can I get a free sample?"},
{id:121,question:"What does it cost me to buy my own prints?"},
{id:124,question:"How much of each sale do I get?"},
{id:337,question:"What are the prices on prints and other products?"},
{category:"Print Approval", catpath:"printsservice/printapproval"},
{id:139,question:"I deleted the deviation and the associated print disappeared. What happened?"},
{id:140,question:"If I am updating an already approved print, why do I need to go through the approval process again?"},
{id:142,question:"My image meets the requirements for a print, why was it rejected?"},
{id:143,question:"What are the requirements for a print to be approved?"},
{id:144,question:"How long does it take for my print to be approved?"},
{id:145,question:"Does the image file I submit to deviantART have to be the same file I submit to Prints?"},
{id:204,question:"If my print contains an image that isn't mine, can I still use it for print?"},
{id:706,question:"Why does my print not display the preview image I have specified in my submission?"},
{id:750,question:"Is permission needed when using collaborative artwork for commercial sales?"},
{id:807,question:"Do I have to provide a Model Release to sell a print?"},
{id:882,question:"Why do print submissions have to undergo quality control?"},
{category:"Print Image Specifications & Requirements", catpath:"printsservice/qualityresolutionaspectratioanddpi"},
{id:126,question:"What size prints are available?"},
{id:127,question:"Can I add blank space to make my products the right size?"},
{id:128,question:"Why can I not resize the image to the correct DPI?"},
{id:129,question:"My piece is not the resolution or DPI you recommend. Can I still sell it?"},
{id:130,question:"Is any image with any resolution or aspect ratio printable?"},
{id:131,question:"Do I have to submit an image at a ratio that exactly matches a print size currently offered by Prints?"},
{id:132,question:"What are the minimum image sizes for each product?"},
{id:134,question:"What does resolution mean?"},
{id:150,question:"I'm not sure if my image quality is OK. How can I tell?"},
{id:152,question:"What is DPI?"},
{id:153,question:"What is aspect ratio?"},
{id:298,question:"What is a bleed edge and how do I use it when preparing my artwork for printing?"},
{id:576,question:"Where can I find templates to help me size my images correctly for prints?"},
{id:702,question:"What do Landscape and Portrait orientation mean?"},
{category:"Deviations & Scraps: Problems & Errors", catpath:"deviantart/deviationsscraps/problemserrors"},
{id:39,question:"I just tried to submit a file to X Category, but it told me the filetype I am trying to upload is not allowed. What can I do?"},
{id:49,question:"Why is my image rotated when I upload it?"},
{id:78,question:"Where do I submit to if I'm not sure?"},
{id:111,question:"Why is the download count not incrementing on my deviation(s)?"},
{id:161,question:"I've submitted over X amount of deviations to a single category, but I am not presented with the option to submit to a frequently used category. Why is this?"},
{id:208,question:"Can I suggest new submission categories to be added?"},
{id:669,question:"Why can I only see mature content submitted by myself and others while I am logged in?"},
{id:670,question:"How come I cannot turn off the Mature Content option on my deviations that are submitted to the Artistic Nude and Fetish Photography sections?"},
{id:754,question:"I do not want others downloading my deviations, how do I disable this option?"},
{id:783,question:"I submitted a deviation or scrap and deviantART did not keep my images original dimensions. Why is this?"},
{id:788,question:"I submitted an image to deviantART but the colors look different then they did on my computer or the image looks blurry or pixelated. Why is this?"},
{category:"My Account: Problems & Errors", catpath:"deviantart/myaccount/problemserrors"},
{id:105,question:"I just uploaded or reset an Avatar, or Lit Tag, and deviantART keeps displaying the old one. Why?"},
{id:114,question:"I forgot my password and need it emailed to me. Where can I do this?"},
{id:641,question:"I need to block more than 500 people from my User Page. Is this possible?"},
{id:660,question:"My deviantART account has been hacked. What can I do?"},
{category:"Problems & Errors", catpath:"orderingsupport/problemserrors"},
{id:721,question:"I see a charge on my credit card even though I was told that my order failed. Did deviantART take my money?"},
{id:733,question:"I suspect my card has been used by someone on deviantART fraudulently. What can I do?"},
{id:734,question:"If my credit card is rejected, will you alert any creditors?"},
{id:735,question:"Why did my credit card work fine on deviantART before, but not now?"},
{id:736,question:"Why was my credit card declined when I am able to use it fine elsewhere?"},
{id:737,question:"Why did my order fail due to connecting from a High Risk location?"},
{id:870,question:"I'm having trouble placing an order. Who should I contact?"},
{category:"Problems & Errors", catpath:"premiummembership/problemserrors"},
{id:48,question:"I have made an error while purchasing a Premium Membership, can I get a refund?"},
{id:65,question:"What will happen to my features once my Premium Membership expires?"},
{id:533,question:"I've changed my mind about my purchase and would like a refund, can I have one?"},
{id:617,question:"During sign up I accidentally selected the 'Paid' membership by mistake. Is there a way to cancel this?"},
{id:748,question:"I received a Premium Membership but did not receive notification of who it was from. Why?"},
{id:785,question:"I paid for a Premium Membership and it said my Premium Membership is activated but I do not have all my features yet. Why is this?"},
{id:823,question:"I selected a Billing Premium Membership Package, but decided I do not want my subscription to auto renew after all. Can I cancel my package?"},
{category:"Problems & Errors", catpath:"deviantfilm/problemserrors"},
{id:43,question:"I've already been accepted to submit film on deviantART and still can't submit film files, can you tell me why?"},
{id:837,question:"My film won't load. What's the problem?"},
{id:840,question:"If my film was made in Flash, can I still upload it?"},
{id:846,question:"My film was removed from the gallery. Why?"},
{id:856,question:"Why can't I change my film file when I edit the deviation?"},
{id:908,question:"My film does not submit through sta.sh, it repeatedly fails, what can I do?"},
{category:"About deviantART: Promoting", catpath:"deviantart/aboutdeviantart/promoting"},
{id:21,question:"Where can I obtain the source files for the deviantART Mascot, Logo, and User Symbols?"},
{id:213,question:"Where are the buttons for linking to deviantART?"},
{category:"Policies: Proper Submitting", catpath:"deviantart/policies/propersubmitting"},
{id:578,question:"What does deviantART consider to be a proper desktop screenshot?"},
{id:634,question:"Why was my deviation relocated or moved?"},
{id:809,question:"What are deviantART's stock image guidelines?"},
{id:818,question:"My wallpaper was removed, can you tell me why?"},
{category:"Policies: Reporting Abuse", catpath:"deviantart/policies/reportingabuse"},
{id:155,question:"How do I report a deviation which I think breaks the rules?"},
{id:238,question:"How do I report people for abuse, harassment, or another issue I think is a problem?"},
{category:"Deviations & Scraps: Scraps", catpath:"deviantart/deviationsscraps/scraps"},
{id:242,question:"What are scraps?"},
{id:243,question:"How do I change an already submitted deviation to a scrap and vice versa?"},
{category:"Search", catpath:"deviantart/search"},
{id:535,question:"Can I search for a random Deviant/Deviation?"},
{id:577,question:"How do I use the Search?"},
{category:"Selling Prints", catpath:"printsservice/sellingprints"},
{id:122,question:"Is there a maximum/minimum selling price?"},
{id:178,question:"How do I know if my print is selling ?"},
{id:261,question:"Where can I view earnings reports and statistics on my Prints, digital content, and Commissions?"},
{id:309,question:"Why do my stats not reflect an order which I know I sold?"},
{id:613,question:"How old do I have to be to sell my prints?"},
{id:640,question:"Are we obliged to declare our prints profits as taxable income?"},
{id:862,question:"Can I use my deviantART Print account to advertise other print stores?"},
{category:"Problems & Errors: Server Issues", catpath:"deviantart/problemserrors/serverissues"},
{id:190,question:"I submitted data to deviantART, but it did not post. Why?"},
{id:505,question:"What does Read-Only Mode mean?"},
{id:701,question:"How come I can still chat on dAMN while in read-only mode, but cannot open a new connection to it?"},
{category:"Shipping", catpath:"printsservice/shipping"},
{id:118,question:"What are the shipping charges?"},
{id:119,question:"Where can prints be shipped?"},
{id:172,question:"How long does it take to receive my order?"},
{id:344,question:"What methods are available for shipping?"},
{id:345,question:"Will other deviants be able to see my shipping address after I add it to my wishlist?"},
{id:498,question:"How long will it take for my order to be shipped?"},
{id:545,question:"Can FedEx ship to Post Office Boxes or APO/FPO military addresses?"},
{id:636,question:"Are there any taxes or charges applied to packages once they cross the border?"},
{id:695,question:"What happens if my order does not arrive or arrives damaged?"},
{id:726,question:"My order arrived but I am missing some items, were they shipped separately?"},
{id:727,question:"How are prints packaged?"},
{category:"About deviantART: Staff", catpath:"deviantart/aboutdeviantart/staff"},
{id:25,question:"Can I be a deviantART administrator?"},
{id:84,question:"What are the Core Values of the Community Relations Department?"},
{id:85,question:"Can I be a volunteer on deviantART?"},
{id:324,question:"What do the Staff Merit Badges stand for?"},
{id:504,question:"Is there an official staff listing?"},
{category:"Stash", catpath:"deviantart/stash"},
{id:440,question:"What is Sta.sh?"},
{id:441,question:"How do I upload to my Sta.sh?"},
{id:442,question:"What is the storage limit of Sta.sh?"},
{id:443,question:"What happens when I reach the storage limit for Sta.sh?"},
{id:444,question:"What happens to my Sta.sh items when my subscription runs out?"},
{id:445,question:"Can I upload anything to Sta.sh?"},
{id:446,question:"Why can't I drag & drop files to my Sta.sh like other users?"},
{category:"My Account: Statistics", catpath:"deviantart/myaccount/statistics"},
{id:164,question:"What is my profile bar and how do I use it?"},
{id:499,question:"What are Gallery Stats, and how can I view them?"},
{id:714,question:"What does the color of the Gallery Stats boxes mean?"},
{id:715,question:"What does the size of the Gallery Stats boxes mean?"},
{category:"Deviations & Scraps: Stock", catpath:"deviantart/deviationsscraps/stock"},
{id:217,question:"What are 'Stock and Resources' and can I use them in my submissions?"},
{category:"Store and Product Management", catpath:"printsservice/storeandproductmanagement"},
{id:622,question:"How do I add, edit, or delete my Prints or digital content?"},
{id:623,question:"How can I modify the appearance and information of my artist store?"},
{id:624,question:"I need help with Prints from a real person! Where can I get it?"},
{id:793,question:"Where can I see how often a deviation of mine has been requested as a Print?"},
{category:"Deviations & Scraps: Submitting", catpath:"deviantart/deviationsscraps/submitting"},
{id:79,question:"How do I submit art?"},
{id:816,question:"How do I upload a collection of images or files, such as brushes, wallpapers or other?"},
{category:"Submitting Products", catpath:"printsservice/submittingproducts"},
{id:146,question:"Do I have to submit an image to deviantART before submitting an image to Prints?"},
{id:149,question:"I can't upload my file. Are there any punctuation limitations on filenames?"},
{id:151,question:"Will I be able to get prints made of my desktop wallpaper?"},
{id:154,question:"Why isn't my source file uploading correctly?"},
{id:182,question:"Why do I need a source file?"},
{id:285,question:"How do I edit an existing print or add more product options to a print?"},
{id:297,question:"When I upload images using FTP, they do not show up in the File Deck."},
{id:559,question:"Are there any guides to aide in the submission of my prints?"},
{id:616,question:"How can I submit an existing deviation as a print?"},
{id:620,question:"How do I submit print products?"},
{id:677,question:"How do I upload my prints using FTP?"},
{id:698,question:"How should I design and submit a calendar?"},
{id:712,question:"Are there any limitations on file upload and the storage of print files?"},
{id:877,question:"How do I use the Adjust Image tool?"},
{id:881,question:"Why does 'Submit Print Step 1 - Select Deviation' not display all of my deviations?"},
{id:890,question:"What do I have to do to not submit a print after submitting a new deviation?"},
{category:"Submitting Questions", catpath:"deviantfilm/submittingquestions"},
{id:832,question:"What file formats are accepted for film?"},
{id:834,question:"What screen size and frame rate should I use for my film submissions?"},
{id:835,question:"If I have a film that is longer than 20 minutes or larger than 200 MB. Can I submit it in to two parts?"},
{id:842,question:"How do I become a submitting member of the film community?"},
{id:843,question:"What is a fan film?"},
{id:845,question:"Can I submit a Fan Film?"},
{id:906,question:"Can I change the thumbnail images attached to the film?"},
{id:907,question:"Can I edit my films on deviantART?"},
{category:"About deviantART: Suggestions", catpath:"deviantart/aboutdeviantart/suggestions"},
{id:798,question:"I think something is missing from deviantART. Where can I go to make my suggestion?"},
{category:"Policies: Unacceptable Content", catpath:"deviantart/policies/unacceptablecontent"},
{id:7,question:"What is the policy concerning photographs of corpses, cruelty or death?"},
{id:12,question:"deviantART doesn't allow 'Hate Art', 'Hate Speech' or 'Hate Propaganda', what is this?"},
{id:60,question:"Do you allow 'Adult', explicit sexual or pornographic content on deviantART? How about linking off site?"},
{id:165,question:"Do you allow images depicting bodily wastes or fluids?"},
{id:284,question:"Can we submit photographs showing actual injury, self-harm and mutilation?"},
{category:"Upgrade to a Super Group", catpath:"groups/upgradetoasupergroup"},
{id:413,question:"What's a Super Group and how can I upgrade?"},
{id:433,question:"How much is a Super Group?"},
{id:434,question:"Who in my group is able to upgrade?"},
{id:435,question:"What happens when my Super Group expires?"},
{category:"Viewing Questions", catpath:"deviantfilm/viewingquestions"},
{id:849,question:"How do I download films, so I can view them later?"},
{id:851,question:"What is an annotation and how can I add one, or read those already added?"},
{id:857,question:"What is 'scrubbing'?"},
{category:"Deviations & Scraps: Wallpaper", catpath:"deviantart/deviationsscraps/wallpaper"},
{id:811,question:"What is a Wallpaper and what should I know about using and making wallapers?"},
{id:821,question:"How do I know what wallpaper resolution will look best on my monitor?"});
FAQloaded=true;