var FAQ = Array({category:"About deviantART", catpath:"deviantart/aboutdeviantart"},
{id:29,keywords:"senior member seniority",question:"How do I become a Senior Member?"},
{id:106,keywords:"symbols symbol staff admin administrator account accounts username status ",question:"What are the symbol next to each deviant's username?"},
{id:116,keywords:"what is deviantart founders founder founded about deviant art",question:"What is deviantART and who founded deviantART?"},
{id:546,keywords:"free account buy purchase",question:"Is deviantART free?"},
{category:"About Points", catpath:"points/aboutpoints"},
{id:234,keywords:"deviant cash money dollars points",question:"What are Points?"},
{id:235,keywords:"deviant cash money funds transaction transactions balance dollars",question:"Where can I find my Points balance?"},
{id:279,keywords:"deviantcash cash dollars money",question:"How do I earn Points?"},
{id:894,keywords:"points lottery raffle",question:"Can I run a lottery for Points on deviantART?"},
{id:895,keywords:"points pageviews donations ",question:"Can I offer an automated service on deviantART in exchange for deviantPOINTS?"},
{category:"About Prints", catpath:"printsservice/aboutprints"},
{id:177,keywords:"account expire prints buy time limit end period new",question:"Does my print account ever expire?"},
{id:179,keywords:"deviantprints daprints da prints what is print",question:"What is deviantART Prints?"},
{id:210,keywords:"machine printers prints qaulity labs ",question:"What technology does the deviantART Prints Service use?"},
{id:338,keywords:"purchase, price, submit, prints, sell, premium",question:"What are the rules for selling prints?"},
{category:"Policies: Abuses & Exploits", catpath:"deviantart/policies/abusesandexploits"},
{id:54,keywords:"flood spam comment",question:"What is 'flooding'?"},
{id:263,keywords:"spam comment profile note forum journal",question:"What is 'spamming'?"},
{id:295,keywords:"abuse favorites devwatch friends page views automatic add ",question:"What exactly is an 'Abuse or Exploit of the System'?"},
{id:574,keywords:"advertis click through ad spam links promo banner",question:"Can I advertise on deviantART without purchasing an official advertising package?"},
{category:"Problems & Errors: Account Creation Issues", catpath:"deviantart/problemserrors/accountcreationissues"},
{id:40,keywords:"I can't create a new account with my email.",question:"I tried to create an account but the email address I tried to use was blocked; why?"},
{id:568,keywords:"banned, IP, isp, internet service provider",question:"I tried to create an account, but it states my IP Address is banned and will not let me continue. Why?"},
{id:649,keywords:"verify account issues problems errors error problem trouble troubles email receive not",question:"I have yet to receive my Verify email. What can I do?"},
{id:650,keywords:"verify verified email account problems errors problem error trouble troubles",question:"I have Verified my email repeatedly and it still reports I need to verify it. What can I do?"},
{category:"Policies: Bans & Suspensions", catpath:"deviantart/policies/banssuspensions"},
{id:221,keywords:"ban banned unban account user use ",question:"I was banned, is there anything I can do?"},
{id:325,keywords:"ban friend admin banning info information",question:"Will you tell me why my friend was banned?"},
{id:610,keywords:"ban suspension banned policy etiquette",question:"What happens when someone is banned or suspended?"},
{category:"Policies: Behavior & Interaction", catpath:"deviantart/policies/behaviorinteraction"},
{id:3,keywords:"comment reply role play roleplay rp etiquette policy rules restriction lewd sexual porn smut erotic ship shipping sex shota pedo loli lolli slash futa note notes profanity swear swearing",question:"Are there restrictions to comments?"},
{id:34,keywords:"journal rules policy",question:"Are there any rules for the journals?"},
{id:214,keywords:"avatar icon policy rule nude nudity mature",question:"What are deviantART's policies regarding avatars?"},
{id:303,keywords:"nazi swasitika hate offen",question:"I'm offended by something I saw on the website!"},
{id:911,keywords:"note report abuse spam",question:"How do I report a Note which I received as spam or as abuse?"},
{category:"Beta Testing", catpath:"premiummembership/betatesting"},
{id:531,keywords:"beta, tester, subscriber",question:"What is an Official deviantART Beta Tester? How do I become one?"},
{id:532,keywords:"beta, tester, subscriber, feedback",question:"As an Official Beta Tester, how do I provide feedback?"},
{id:541,keywords:"beta tester opt-out testing",question:"If I'm a beta tester, may I choose to opt-out of the program later?"},
{category:"Browsing & Comments: Browsing", catpath:"deviantart/browsingcomments/browsing"},
{id:44,keywords:"mobile deviantmobile interface wii",question:"I am a mobile interface user, but I do not wish to use this interface. How can I disable it?"},
{id:45,keywords:"channels customize",question:"What are Channels and how do I use them?"},
{id:125,keywords:"sitback sit back browse",question:"What is SitBack and how do I use SitBack?"},
{id:333,keywords:"idle last visited online status",question:"What does it mean when a user's page says 'is currently idle' or 'last visited'?"},
{id:608,keywords:"browse user gallery category",question:"Can I browse a user's gallery by a specific Category?"},
{id:642,keywords:"browse omg how do i 60 120",question:"How do I use the Browse interface?"},
{category:"Buying Prints", catpath:"printsservice/buyingprints"},
{id:173,keywords:"Shipping mail locations costs shipment shipments damaged missing",question:"What if my order is damaged when I receive it?"},
{id:175,keywords:"buy buying pricing credit card purschasing ",question:"Is there tax on prints?"},
{id:181,keywords:"buy buying pricing credit card purchasing paypal points echeck debit",question:"Can I still buy prints if I don't have a credit card?"},
{id:188,keywords:"frame buy framing print",question:"Can I buy a frame with my prints?"},
{id:194,keywords:"buy buying pricing credit card purschasing country outside foreign",question:"Can I buy prints for someone outside my country?"},
{id:195,keywords:"buy buying pricing credit card purschasing country outside foreign",question:"Do I have to buy a frame to get my print?"},
{id:198,keywords:"buy buying pricing credit card purschasing ",question:"Is there a discount on bulk orders?"},
{id:619,keywords:"orders returns damaged refunds time limit return cancel edit change subscription premium membership",question:"Is there a time limit regarding reporting unsatisfactory orders?"},
{id:738,keywords:"phone telephone support customer service help ordering orders question",question:"Can I place an order or speak to a representative over the phone?"},
{id:771,keywords:"order status details ",question:"Where can I check my order status and details?"},
{id:884,keywords:"buyer customer buy purchase cart checkout login signup register log sign account",question:"How do I login to or signup for a buyer account?"},
{id:893,keywords:"print lab shop store process produce receive ship send order manufacture ",question:"Who processes and ships the prints orders?"},
{category:"Campaign Questions", catpath:"adcast/campaignquestions"},
{id:600,keywords:"advertisement adcast clicks campaign ",question:"How do I know how successful my campaign was?"},
{id:780,keywords:"file types adcast submissions campaign",question:"What kind of file types can I submit for my AdCast campaign?"},
{id:782,keywords:"adcast campaign start run date",question:"How long will it take for my campaign to start?"},
{id:888,keywords:"campaign clicks pageviews",question:"Why don't my site pageviews match the number of clicks my campaign report says I received?"},
{category:"Chat Network & Forums: Chatroom Customization", catpath:"deviantart/chatnetworkforums/chatroomcustomization"},
{id:17,keywords:"chat tutorial lesson ",question:"I just created my chatroom and I’m confused.  Are there any tutorials?"},
{id:291,keywords:"damn, description, chat",question:"Can I change the description of my chatroom?"},
{id:507,keywords:"advanced, DAmn, private room, unlist",question:"How do I make a private room?"},
{id:510,keywords:"DAmn Bot",question:"What is a bot, and how can I get one?"},
{id:513,keywords:"change title topic",question:"How do I change the title (or topic) on the top of my chatroom?"},
{id:540,keywords:"chat custom groups damn dAmn admin priv privclass privs",question:"How can I customize my chatroom?"},
{category:"Problems & Errors: Comment Issues", catpath:"deviantart/problemserrors/commentissues"},
{id:31,keywords:"500 spam post cannot comment ",question:"I am unable to post comments or send notes because the site informed me I was spamming. What is going on?"},
{id:351,keywords:"nobody empty comment 1970 1969",question:"What does it mean if I receive or see a comment from 'Nobody'?"},
{category:"Browsing & Comments: Comments", catpath:"deviantart/browsingcomments/comments"},
{id:14,keywords:"link linking comment comments specific",question:"How do I create a link to a specific comment?"},
{id:41,keywords:"parent top reply",question:"What do the 'Parent', 'Top' and 'Reply' links under comments mean?"},
{id:160,keywords:"delete comments comment deletion remove removed hide",question:"Can I remove or delete comments on my userpage, journal or deviations?"},
{id:661,keywords:"comments comment post",question:"How do I post a comment?"},
{category:"Commissions", catpath:"premiumcontentplatform/commissions"},
{id:370,keywords:"commissions, commission, premium content platform, premium content ",question:"What are Commissions?"},
{id:371,keywords:"commissions, commission, premium content platform, premium content",question:"When do I have to pay for a commission?"},
{id:372,keywords:"commissions, commission, premium content platform, premium content, paid, earnings",question:"When do I get paid for my Commission?"},
{id:373,keywords:"commissions, commission, premium content platform, premium content, dispute",question:"What happens if an artist doesn't deliver a Commission?"},
{id:374,keywords:"commissions, commission, premium content platform, premium content, dispute",question:"How do I settle a Commission dispute?"},
{id:375,keywords:"commissions, commission, premium content platform, premium content",question:"I requested a Commission, but the artist still hasn't accepted or rejected it, what can I do?"},
{id:899,keywords:"commissions, commission, premium content platform, premium content",question:"Why can't I use credit cards or PayPal on Premium Content Platform and Commissions purchases?"},
{id:904,keywords:"commissions, commission, premium content platform, premium content ",question:"How do I get to the Commissions shop?"},
{category:"Content Questions", catpath:"adcast/contentquestions"},
{id:594,keywords:"advertisement, adcast, banner",question:"What size should my advertisement be?"},
{id:595,keywords:"advertisement adcast",question:"When you say 'Anything having to do with a corporation or commercial content of any kind'; does that mean I cannot link my advertisements to my website where I can make money off my art?"},
{id:596,keywords:"advertisement adcast nude nudity content ",question:"Can I advertise for my erotic art site?"},
{id:597,keywords:"advertisement adcast nude nudity erotic content",question:"Can I submit an advertisement which contains nudity or erotic content?"},
{id:744,keywords:"adcast content ",question:"What should my advertisement look like?"},
{id:779,keywords:"adcast sized banner 300x250 other",question:"Can I submit a different sized banner other than 300x250 for my AdCast campaign?"},
{category:"Problems & Errors: Cookies & Cache", catpath:"deviantart/problemserrors/cookiescache"},
{id:643,keywords:"cache clear problem error browser trouble",question:"I was asked to clear my browser's cache. How do I do this?"},
{id:644,keywords:"cookies enable problems errors problem error browser trouble login",question:"I was told to make sure my cookies are properly enabled. How do I do this?"},
{id:645,keywords:"cookies delete problems errors problem error browser trouble login",question:"I was told I should try deleting my cookies. How do I do this?"},
{category:"Policies: Copyright Concerns", catpath:"deviantart/policies/copyrightconcerns"},
{id:8,keywords:"theft plagiarism copyright policy use dmca digital millennium infringe steal stealing copy trace ",question:"What are violations of the deviantART copyright policy?"},
{id:32,keywords:"fair use submission copyright",question:"Fair Use and Your Submission"},
{id:63,keywords:"poetry preview thumb prose literature lit",question:"What sort of things can I use for Preview images?"},
{id:501,keywords:"warez software product keygen crack copy copies journal",question:"What are 'warez', 'cracks' and 'keygens'? Do you allow those?"},
{id:614,keywords:"music flash film use theft permission animation submission",question:"What can I use for music tracks and sound effects in my animation or film?"},
{id:814,keywords:"signature watermark copyright ",question:"Should I put a signature, watermark or copyright notice on my art before submitting it?"},
{category:"Copyrights", catpath:"printsservice/copyrights"},
{id:743,keywords:"fanart fan art character movie comic tv television copyright trademark",question:"Can I sell fan art as prints?"},
{id:751,keywords:"permission collab legal copyright",question:"Is permission needed when using collaborative artwork for commercial sales?"},
{id:752,keywords:"stock rights approval permissions legal illegal copyright ",question:"If my print contains an image that isn't mine, can I still use it for print?"},
{id:792,keywords:"permission stock resource brush texture font",question:"As a stock art resource provider, how can I be of help in regards of stock art resource usage in prints?"},
{id:828,keywords:"vintage public domain artwork sell",question:"Can I sell vintage artwork in my deviantART Print Store?"},
{category:"Critique Feature", catpath:"premiummembership/critiquefeature"},
{id:95,keywords:"critique subscriber subscription feature comment",question:"What is the Critique Feature and how do I use it?"},
{category:"Deviations & Scraps: Daily Deviation", catpath:"deviantart/deviationsscraps/dailydeviation"},
{id:18,keywords:"daily deviation dd dailydevs suggestion feature award choose",question:"Who selects Daily Deviations and how are they chosen?"},
{id:61,keywords:"daily deviation dd dailydevs suggestions suggestion feature award",question:"What is a Daily Deviation?"},
{id:313,keywords:"daily deviation ",question:"How can I find out if someone already has a Daily Deviation?"},
{id:873,keywords:"disagree disapprove dd daily deviation problem have dislike complain",question:"What do I do when I disapprove of a Daily Deviation feature?"},
{category:"deviantART T-shirts & Gear Design Battle", catpath:"deviantarttshirtsgear/deviantarttshirtsgeardesignbattle"},
{id:270,keywords:"deviantwear vote challenge design contest",question:"How do I vote in a deviantART contest or design challenge?"},
{id:271,keywords:"cancel vote deviantwear design challenge contest",question:"Can I cancel a vote?"},
{id:272,keywords:"deviantwear vote challenge design contest",question:"Why I am having trouble voting?"},
{id:273,keywords:"deviantwear vote challenge design rights contest",question:"Do I still own rights to my image after submitting the image to a deviantART contest?"},
{id:274,keywords:"deviantwear vote challenge design contest",question:"How often can I vote in a deviantART contest or challenge that uses the voting platform?"},
{id:275,keywords:"deviantwear vote challenge design contest",question:"How does deviantART prevent users from cheating during the voting for its contests?"},
{category:"My Account: deviantWATCH", catpath:"deviantart/myaccount/deviantwatch"},
{id:19,keywords:"devwatch friends notify remove delete",question:"If I remove someone from my deviantWATCH, will they be notified?"},
{id:26,keywords:"deviantwatch devwatch friends watch add +watch +friend +devwatch",question:"What is the deviantWATCH and how do I manage my deviantWATCH listing?"},
{id:68,keywords:"deviant watch friends list remove devwatch stalker stalkers block ",question:"Can I remove someone who is watching me?"},
{category:"Problems & Errors: Display Issues", catpath:"deviantart/problemserrors/displayissues"},
{id:75,keywords:"error red x deviation image load trouble problem error",question:"Many images will not load for me or all I see is red x's. Why?"},
{id:638,keywords:"css white funny tables text purple ",question:"Sometimes deviantART loads funny in my browser. What causes this?"},
{id:647,keywords:"firefox stopped fail failed load loading problems errors problem error browser trouble",question:"I'm a Firefox user and images have stopped loading in my browser. How can I fix this?"},
{id:664,keywords:"dash illegal user username problem",question:"My friends username has a dash before, after it or both and I cannot access their page. Why is this?"},
{id:672,keywords:"animations no longer play stopped working play animate avatar issue problem error stop work emotes",question:"I can no longer see animations such as avatars and emoticons play on deviantART and possibly elsewhere. What could be causing this?"},
{category:"Deviations & Scraps: Downloading", catpath:"deviantart/deviationsscraps/downloading"},
{id:64,keywords:"tutorials, download",question:"How do I download Tutorials?"},
{id:602,keywords:"brushes Brushes photoshop brushes",question:"How do I download Brushes?"},
{category:"My Account: Edit Settings & Profile", catpath:"deviantart/myaccount/editsettingsprofile"},
{id:4,keywords:"avatar, signature, lit tag, literature, password, contact, stats, pageview, status, mention button, information, real, email, displayed email, blocked users, browsing, comments, beta, testing currency change username session apps uploads rebilling",question:"Which options can I control under the Edit Settings page?"},
{id:93,keywords:"hide mature content button checkbox mobile ios android",question:"How does the Mature Content option work?"},
{id:147,keywords:"avatar upload how icon",question:"How do I upload or remove an avatar for my profile?"},
{id:912,keywords:"mature content settings mobile app ios android",question:"How do Mature Content settings work in the DeviantArt Mobile App?"},
{category:"Help Desk & FAQ: FAQ", catpath:"deviantart/helpdeskfaq/faq"},
{id:158,keywords:"add question faq update",question:"I think something is missing from the FAQ."},
{id:606,keywords:"error typo error mistake faq correct",question:"I found an error in the FAQ. Where can I report this?"},
{category:"Deviations & Scraps: Favourites", catpath:"deviantart/deviationsscraps/favourites"},
{id:11,keywords:"deviations deviation favs favourites favourite",question:"Is there a way to see which deviants have added my deviation submission to their favourites?"},
{id:59,keywords:"remove delete favs favourites favourite favorite favorites",question:"How do I add and delete Favourites?"},
{category:"File Formats", catpath:"printsservice/fileformats"},
{id:136,keywords:"file formats jpeg jpg png bmp color colour rgb cmyk ",question:"Should I submit print images as RGB or CMYK?"},
{id:137,keywords:"image file format jpeg jpg png bmp",question:"What are the advantages/disadvantages of each image file format?"},
{id:138,keywords:"file formats jpeg jpg gif png bmp",question:"What file types are accepted by Prints?"},
{id:176,keywords:"file formats jpeg jpg png bmp",question:"What are JPEG, PNG, and BMP files?"},
{category:"Problems & Errors: Firewall Issues", catpath:"deviantart/problemserrors/firewallissues"},
{id:653,keywords:"dos attack syn attack firewall software problem errors error report wtf",question:"My Firewall reported that deviantART is trying to attack me. Why is this happening?"},
{category:"Deviations & Scraps: Gallery Management", catpath:"deviantart/deviationsscraps/gallerymanagement"},
{id:199,keywords:"mature content tag nude nudity naked blood violence submit penis vagina cock cunt sex film",question:"How do I add Mature Content tag to my deviation?"},
{id:299,keywords:"personal, gallery, management, tools, comment, critique",question:"What are my Personal Gallery Management Tools, and how do I get to them?"},
{id:307,keywords:"deviation, storage, hide, enable, disable, gallery, manage, management, out of sight, sight, backroom, temporarily",question:"What is the Deviation Storage Tool, and how do I access it? Can I temporarily hide deviations?"},
{id:554,keywords:"mature content tag nude nudity naked blood violence submit penis vagina cock cunt sex sexual film fanart fanfiction fic fanfic porn loli pedo shota ship shipping minor underage",question:"Is my deviation Mature Content?"},
{category:"General", catpath:"printsservice/general"},
{id:135,keywords:"quality paper kodak archive archival",question:"What is the print quality like?"},
{id:183,keywords:"glossy matte print paper finish finishes",question:"What is a glossy finish?"},
{id:184,keywords:"glossy matte print paper",question:"What is a matte finish?"},
{id:185,keywords:"glossy matte print paper lustre finish",question:"Which is better, Glossy, Matte or <i>Lustre</i>® finishes?"},
{id:222,keywords:"preview devation size print image buy screen",question:"Why is my print preview so small?"},
{id:230,keywords:"wishlist purchase ",question:"How do I purchase items for someone from their wishlist?"},
{id:280,keywords:"lustre finish",question:"What is a <i>Lustre</i>® finish?"},
{id:281,keywords:"product description print canvas mouse pad mug postcard coaster magnet panoramic pano greeting cards greeting card paper longevity quality",question:"What are the products offered by the deviantART Prints service?"},
{id:551,keywords:"calendar, year",question:"When will the Calendar year change over for any Calendars I have submitted?"},
{id:603,keywords:"canvas printing photograph",question:"How would a photograph look printed on canvas?"},
{id:604,keywords:"canvas print mount mount stretch wooden wrap frame",question:"What are Wrapped Canvas prints mounted on?"},
{id:605,keywords:"wishlist notify notification",question:"How can I tell who added my print to their wishlist?"},
{id:775,keywords:"group, club, multiple, share, collab, print account",question:"Can more than one person use a Print Account?"},
{id:794,keywords:"coffee ceramic mug cup ",question:"How will the artwork be displayed on coffee mugs?"},
{id:808,keywords:"shop product merch item print canvas magnet postcard mug cup coffee puzzle calendar coaster mouse pad",question:"What do the products offered by the deviantART Prints Service look like?"},
{id:876,keywords:"how search use specific find product item shop store print canvas coffee ceramic mug coaster mouse pad calendar magnet puzzle postcard",question:"How do I use the Shop Search?"},
{id:879,keywords:"wish list wishlist manage",question:"What is the Wishlist and how do I manage my Wishlist?"},
{id:885,keywords:"canvas print mount mounted wooden wrap frame stretch",question:"What is the difference between Wrapped Canvas and Rolled Canvas?"},
{category:"Deviations & Scraps: General", catpath:"deviantart/deviationsscraps/general"},
{id:10,keywords:"deviations deviation delete gallery remove",question:"Will the deviantART staff remove all my deviations for me because it takes too long for me to delete deviations one by one?"},
{id:15,keywords:"what deviation description",question:"What is a deviation?"},
{id:70,keywords:"keywords, deviation, deviations",question:"What is the format for the Keywords in deviations and what are they for?"},
{id:72,keywords:"deviation deviations delete remove",question:"How do I edit or delete my deviation or scrap submissions?"},
{id:163,keywords:"Gallery Tier Guidelines sections catagory catagories description descriptions",question:"Where can I find the description to a Gallery that I want to submit to?"},
{id:211,keywords:"EXIF camera make model shutter speed focal length ISO statistics stats photo photos exif photograph",question:"How do I get my camera's specifications to show or not show up when I submit a picture?"},
{id:332,keywords:"watermark watermarking protect copyright",question:"Does deviantART have a feature that will automatically watermark my deviations?"},
{id:552,keywords:"submit deviations gallery limit maximum cap",question:"Is there a limit to how many deviations I can submit?"},
{id:666,keywords:"edit notify watchers watchlist my renotify will the edit",question:"Will my watchers be notified of my deviation and scrap submission edits?"},
{id:753,keywords:"limit size deviation deviations limitation poetry prose char character text punctuation chopped off words missing literature",question:"Are there any limitations for deviation submissions?"},
{id:872,keywords:"music audio mp3 wav flac m4a aac wma",question:"Does deviantART allow music submissions?"},
{category:"My Account: General", catpath:"deviantart/myaccount/general"},
{id:56,keywords:"noticed pageviews comment feedback popular known",question:"How can I get noticed on this site?"},
{id:112,keywords:"nickname change nick user accounts username name nickname rename",question:"How do I change my deviantART username?"},
{id:113,keywords:"delete user accounts close terminate deactivate deactivation reactivate",question:"Can I delete my deviantART account?"},
{id:201,keywords:"unused, dead, accounts, close, delete, release to public take over inactive ",question:"Do you close unused accounts, or release them to the public?"},
{id:662,keywords:"avatar how to create display icon do i get i want",question:"How do I create an Avatar, to display on my User Page and next to my Comments?"},
{id:673,keywords:"how to club create group groups make",question:"How can I make a club or group?"},
{id:745,keywords:"private message note",question:"How can I send a note to another deviant?"},
{category:"Problems & Errors: General", catpath:"deviantart/problemserrors/general"},
{id:24,keywords:"spam report tagged comment",question:"I just tagged someones comment as spam by mistake, will anything happen to the user?"},
{id:57,keywords:"issue status forum ",question:"I see one of my issues listed in the Status Forum, but I do not see 'all' of my issues listed. What do I do?"},
{id:656,keywords:"find user username friend nickname locate search",question:"My friend gave me their deviantART username, but I have no clue how to locate them. How do I do this?"},
{id:716,keywords:"java javascript ",question:"I was told to make sure I have Javascript enabled. How do I do this?"},
{id:719,keywords:"status forum fixed issue bug",question:"I read in the 'Status Forum' that an issue was fixed but I think it's happening again. Why is this?"},
{id:722,keywords:"fix bug error",question:"Why do certain bugs take longer than others to be fixed?"},
{id:723,keywords:"test bug fix error tested release ",question:"How come things are not better tested before they are released?"},
{id:724,keywords:"release bug test broken error ",question:"Why do you put out new features when things are broken?"},
{id:756,keywords:"update browser how do i updating upgrade",question:"I was told to update my browser. How do I do this?"},
{id:859,keywords:"create link help desk team supply give links comment",question:"I was asked by an administrator in the Help Desk to supply a link to my image, comment, forum thread, etc. How do I include a link in my reply?"},
{id:861,keywords:"screenshot help desk admin",question:"How do I take a screenshot for my Help Desk ticket?"},
{category:"Chat Network & Forums: General", catpath:"deviantart/chatnetworkforums/general"},
{id:50,keywords:"forum locked closed restricted error",question:"Why do I receive 'posting restricted errors' when replying to a forum thread?"},
{id:51,keywords:"forum locked closed restricted lock",question:"Why do my threads keep getting closed?"},
{id:58,keywords:"shout box shoutbox chat room",question:"Where is the Shoutbox?"},
{id:288,keywords:"damn, icon, official, chat",question:"What does the Fella icon by a chatroom name mean?"},
{id:289,keywords:"damn, create, make, chat, remove, delete",question:"How do I create or delete a chatroom?"},
{id:290,keywords:"manage, damn, chat, operators, member",question:"How do I manage the users in my chatroom, and set operators and members?"},
{id:292,keywords:"commands, damn, chat",question:"What are the commands that I can use on the chat network?"},
{id:293,keywords:"browser, damn, requirements, problems, chat, issues, error, 128, connect, safari",question:"Why am I having technical issues using the Chat Network?"},
{id:294,keywords:"damn, chat, what",question:"What is dAmn?"},
{id:508,keywords:"DAmn, post code, emoticon, raw",question:"How do I post the raw HTML or emoticon codes in chatrooms?"},
{id:511,keywords:"thumbshare thumbnail DAmn thumb forum ",question:"How do I post thumbnails of my art on the Chat Network or Forums?"},
{id:512,keywords:"whois dAmn where friends locate",question:"How do I know where my friends are chatting?"},
{id:514,keywords:"more rooms chatroom multiple join",question:"Can I join more than one room in a single browser?"},
{id:618,keywords:"forum chat ",question:"Does deviantART have a Forum system?"},
{id:709,keywords:"thread close closure lock locked closed forum post",question:"Can I close or delete my forum thread?"},
{id:874,keywords:"dAmn MN@ purpose  #help helpers",question:"What is the purpose of the #help chatroom?"},
{category:"General deviantART T-shirts & Gear Questions", catpath:"deviantarttshirtsgear/generaldeviantarttshirtsgearquestions"},
{id:580,keywords:"ship deviantART T-Shirts & Gear time approx where is my order my order wear clothes hat hoodie shirt return refund exchange",question:"What are the return and exchange policies for deviantART T-Shirts & Gear merchandise?"},
{id:583,keywords:"deviantART T-Shirts & Gear order time ",question:"How long does it take to receive my deviantART T-Shirts & Gear order?"},
{id:900,keywords:"purchase deviantART Gear Items",question:"Why can’t I find a way to purchase deviantART Gear Items?"},
{id:901,keywords:"How long",question:"How long does it take to receive my deviantART T-Shirts & Gear order?"},
{id:902,keywords:"does not arrive or arrives damaged",question:"What happens if my order does not arrive or arrives damaged?"},
{category:"General Group Questions", catpath:"groups/generalgroupquestions"},
{id:400,keywords:"group join member user",question:"I created a group but users cannot join. How do I let them?"},
{id:401,keywords:"group problem issue reset fix help",question:"I’m experiencing problems with my group, what can I do?"},
{id:402,keywords:"group admin action permission vote accept deny invite",question:"I’m an admin in a group but cannot perform administrative actions, why?"},
{id:403,keywords:"groups group club profile",question:"How will others know that I’m part of a group? How do I know what groups I'm in?"},
{id:404,keywords:"group avatar banner icon image",question:"How do I upload an avatar for my group and what are the limitations?"},
{id:405,keywords:"group leave unjoin",question:"How do I leave a group I no longer wish to be a part of?"},
{id:406,keywords:"group deviation gallery folder remove",question:"How do I remove a user’s deviation from my groups gallery/favs?"},
{id:407,keywords:"group deviation gallery folder remove",question:"How do I remove my deviations from a group?"},
{id:408,keywords:"Group delete deactivate close remove",question:"Can I delete my group?"},
{id:409,keywords:"group founder leave remove replace ",question:"As the founder can I appoint someone to replace me?"},
{id:410,keywords:"group official deviantart",question:"What are the official deviantART groups?"},
{id:411,keywords:"group club groups administrator admin founder co-founder contributor moderator",question:"What’s the difference between a group administrator and a non-administrator?"},
{id:416,keywords:"group club groups changes updates",question:"How will I be notified when changes are made to my group?"},
{id:417,keywords:"group club groups  founders administrators promote demote members member",question:"How do Founders or other administrators promote, or demote, their members?"},
{id:422,keywords:"groups group club how many join",question:"How many groups can I join?"},
{id:430,keywords:"groups group club member submit deviations gallery",question:"Can any member of the group submit deviations to the group's gallery?"},
{id:431,keywords:"groups group club sell prints profits",question:"Can a group sell prints? If so, where do the profits go?"},
{id:432,keywords:"groups group club Message Centre center activity ",question:"Where will my Groups activity go in my Message Centre?"},
{category:"General Premium Membership Questions", catpath:"premiummembership/generalpremiummembershipquestions"},
{id:28,keywords:"subscription subscriptions purchase sub buy benefits premium member membership",question:"What are the benefits of becoming a Premium Member?"},
{id:148,keywords:"paypal subssub subscriptions subscription money order orders dollars dollar credit card visa check purchase buy moneyorder points premium",question:"What methods of payment are accepted for purchasing deviantART Premium Membership Packages?"},
{id:228,keywords:"transfer subscription premium",question:"Can I transfer my deviantART Premium Membership?"},
{id:236,keywords:"premium membership auto renew",question:"Will my deviantART Premium Membership be auto renewed?"},
{id:253,keywords:"subsribe subscription replaced overwritten remaining existing premium",question:"If I have a Premium Membership and purchase another, what happens to the existing Premium Membership?"},
{id:518,keywords:"credit card, fraud, unauthorized, subscription, purchase, premium",question:"Can I use another person's credit card to purchase a Premium Membership?"},
{id:749,keywords:"email confirmation receipt notify",question:"If I purchase a Premium Membership to deviantART will I receive an email confirming my purchase?"},
{id:824,keywords:"billing subscription package prepaid rebill rebilling",question:"What is the difference between a Prepaid Premium Membership Package and a Billing one?"},
{id:825,keywords:"rebilling premium membership package monthly subscription",question:"How do I cancel my rebilling Premium Membership?"},
{category:"General Questions", catpath:"adcast/generalquestions"},
{id:591,keywords:"advertisement, adcast",question:"Where will my advertisement show up and who will see it?"},
{id:592,keywords:"advertisement, adcast",question:"How long will my campaign run?"},
{id:593,keywords:"adcast advertising advertisement promotion ",question:"Can I buy both Homepage and Profile Page, or can I only buy one?"},
{id:598,keywords:"advertisement adcast banner size adcast",question:"The last time I purchased an AdCast package, the advertisement size was different. Why?"},
{id:728,keywords:"adcast advertising advertisement promotion movie trailer",question:"There was a movie trailer takeover on the homepage.  What was that?"},
{id:729,keywords:"adcast advertising advertisement promotion ",question:"Why can’t I see my ad on the homepage?"},
{id:730,keywords:"adcast advertising advertisement promotion  frequency capping",question:"What is 'frequency capping'?"},
{id:739,keywords:"what is adcast ad cast advertising promotion",question:"What is AdCast?"},
{id:740,keywords:"adcast advertising advertisement promotion ",question:"Who will see my ad?"},
{id:746,keywords:"adCast ad cast contact",question:"I have a question about AdCast not covered in the FAQ. Who can I contact for further information?"},
{id:747,keywords:"adcast advertising advertisement promotion impression",question:"What is an 'impression'?"},
{id:757,keywords:"adcast advertising advertisement promotion",question:"What other ads will I see on the deviantART Homepage?"},
{id:758,keywords:"adcast advertising advertisement promotion clicks",question:"Am I guaranteed a certain number of clicks on AdCast Homepage ads?"},
{id:777,keywords:"adCAST Gift Prize different user not myself",question:"I want to buy an AdCast subscription for another person, either as a gift or a prize for a contest I am running. How can I do this?"},
{id:781,keywords:"refund adcast satisfied policies money return",question:"I am not happy with my AdCast order. What are the AdCast refund policies?"},
{category:"General Questions", catpath:"orderingsupport/generalquestions"},
{id:27,keywords:"order history recent past general purchase purchases",question:"How do I locate my order history?"},
{id:52,keywords:"wishlist purchase ",question:"How do I purchase items for someone from their wishlist?"},
{id:631,keywords:"safe credit card safety my secure purchase subscription money",question:"Is it safe to use my credit card at deviantART?"},
{id:731,keywords:"cvv credit card code my purchase subscription money subscribe order",question:"What is a CVV Code and where can I find mine?"},
{id:732,keywords:"verified by visa secure code credit card ordering order purchase purchasing mastercard master card approved",question:"What is Verified by Visa or SecureCode and why do I need to use it?"},
{id:774,keywords:"phone talk to someone call deviantART phone number speak representative",question:"Can I place an order or speak to a representative over the phone?"},
{category:"General Questions", catpath:"deviantfilm/generalquestions"},
{id:831,keywords:"film films submit rules anyone submission guidelines",question:"Why can't just anyone submit film?"},
{id:836,keywords:"invite invitation film films submit submission submitting",question:"How does the 'Film' invitation process work?"},
{id:847,keywords:"deviantART make produce film films",question:"Does deviantART make films?"},
{id:848,keywords:"deviantART film films dist distribution",question:"Does deviantART offer film distribution?"},
{id:852,keywords:"music film find locate films",question:"Where can I find music for my films?"},
{id:853,keywords:"convert compress video film",question:"How can I convert or compress my videos?"},
{id:855,keywords:"chat discuss film films",question:"Is there a chat room for film?"},
{category:"About deviantART: General Use", catpath:"deviantart/aboutdeviantart/generaluse"},
{id:9,keywords:"limit limitation thumbnail emoticon thumbs",question:"What are the limits for Thumbnails and Emoticons?"},
{id:30,keywords:"update up to date new news change chagnes status bug",question:"How can we stay informed about new changes, updates, and technical problems with deviantART?"},
{id:38,keywords:"support browser browsers deviantart ie firefox safari mobile os device",question:"Which browsers and Mobile OS are supported by deviantART?"},
{id:46,keywords:"footer community",question:"How do I use the Community Footer found on main deviantART pages?"},
{id:53,keywords:"emotes icons faces",question:"How do I use Emoticons? Where are they?"},
{id:81,keywords:"links link linking credit deviant avatar icon deviants markup HTML acronym popup tips tooltips work deviations image code film embed youtube thumb thumbnail vimeo soundcloud",question:"How can I create links to other deviants, deviations, or websites?  <da:embed profile='youtube' id='eWM2joNb9NE' />"},
{id:104,keywords:"format formatting html code style tags text words letters word letter tag bold italic underline strike script super acronym markup",question:"What HTML formatting can we use on deviantART? And what is the format for these codes?"},
{id:133,keywords:"deviantART contest US-only US",question:"Why does dA have US Only Contests?"},
{id:335,keywords:"rss journal syndication",question:"What are RSS feeds and how do I use them?"},
{id:790,keywords:"flash preloader pre load official deviantART",question:"Where can I download the Official deviantART Flash preloader?"},
{category:"Gift Premium Memberships", catpath:"premiummembership/giftpremiummemberships"},
{id:55,keywords:"sub buy someone renew notify notification automatic auto personal info information",question:"I wish to purchase a Gift Premium Membership for another member, what should I know?"},
{category:"Guides", catpath:"deviantfilm/guides"},
{id:830,keywords:"deviation submit upload submission submitting gallery description art film ",question:"How do I submit Film?"},
{category:"Help Desk & FAQ: Help Desk", catpath:"deviantart/helpdeskfaq/helpdesk"},
{id:215,keywords:"help request ignored no response ticket reply most experience",question:"I have not received a response to my Help Desk Inquiry? What could be the reason or reasons for this?"},
{id:264,keywords:"help desk helpdesk description catagories category",question:"Is there a description of the Help Desk contact categories?"},
{id:538,keywords:"email help desk community e-mail mail",question:"I can't log in to use the Community Help Desk, is there an email?"},
{id:590,keywords:"help desk inquiry hours operation ",question:"What are the hours of operation for the Help Desk?"},
{id:630,keywords:"policy rules help desk banned",question:"Are there any rules for the Help Desk?"},
{id:713,keywords:"who help desk team staff ",question:"Who is on the Help Desk Team?"},
{id:741,keywords:"help desk helpdesk reply respond email e-mail receive inquiry ",question:"How are Help Desk responses sent to me? Can I have them e-mailed to me?"},
{id:742,keywords:"help desk reply respond email e-mail receive inquiry unable ",question:"I am unable to receive or see messages at this time in my 'Message Centre'. Does this also mean I cannot receive or see Help Desk responses?"},
{id:767,keywords:"link to create a help desk",question:"Can I create a link to the Help Desk?"},
{category:"My Account: Journal", catpath:"deviantart/myaccount/journal"},
{id:62,keywords:"skins journal css html",question:"How do I use Journal skins?"},
{id:66,keywords:"css skins images thumbnails thumb image print shop journal thumbs",question:"What journal features do I have access to?"},
{id:67,keywords:"skins share generous journal blog",question:"How do I share Journal Skins?"},
{id:69,keywords:"journal animated background flash seizure flashing",question:"Can I use animated images within my journal, journal CSS or journal background?"},
{id:100,keywords:"add edit journal entries delete blog",question:"How do I add, edit or delete journal entries?"},
{id:101,keywords:"cutomize journal widget widgets shoutbox forum polls custom",question:"How do I customize my journal page?"},
{id:197,keywords:"avatar, limit, icon",question:"How many avatars am I allowed to post in my journal?"},
{id:892,keywords:"skins journal css html",question:"What is the file format for Journal skins?"},
{id:910,keywords:"journal mobile",question:"Why don't some Journals display properly on my mobile phone?"},
{category:"Problems & Errors: Login Issues", catpath:"deviantart/problemserrors/loginissues"},
{id:115,keywords:"password username login refresh reloads",question:"I entered my username and password correctly but am not able to login. Why?"},
{category:"Problems & Errors: Lost Password Issues", catpath:"deviantart/problemserrors/lostpasswordissues"},
{id:657,keywords:"spam bulk lost pass password trouble problem error errors problems troubles",question:"I have yet to receive my Lost Password email. What can I do?"},
{id:658,keywords:"confirmation code lost pass password trouble problem error errors problems troubles key",question:"I received the confirmation code, but deviantART tells me it's invalid. What can I do?"},
{id:659,keywords:"forgot, username, user, name, account, lost password invalid email",question:"I forgot my username or I have lost my password and forgot to update my email address on file. What can I do?"},
{category:"Make a Group", catpath:"groups/makeagroup"},
{id:418,keywords:"groups group what create",question:"What are Groups and how do I make one?"},
{id:419,keywords:"groups group club free cost ",question:"Are Groups free?"},
{id:421,keywords:"groups group club how many create",question:"How many groups can I make at one time?"},
{id:423,keywords:"groups group club how many administrator admin moderator",question:"Why is there a limit on how many groups I can be an administrator of?"},
{id:425,keywords:"groups group club submit application ",question:"What happens after I submit my application?"},
{id:428,keywords:"groups club create premium membership expire administrator ",question:"What happens when my Premium Membership expires and and I am an administrator of more than three (3) groups?"},
{id:429,keywords:"groups group club admin area",question:"What is the 'Admin Area'?"},
{category:"Policies: Mature Content & Pornography", catpath:"deviantart/policies/maturecontentpornography"},
{id:13,keywords:"Mature content porn tag smut lemon lime role play rp sex yaoi yuri shota mc flag warning disclaimer lit literature fic fan art porn lemons warn porn pornography ",question:"Does a Mature Content tag make it safe for me to submit whatever I want?"},
{id:251,keywords:"nudity censorship naked policy nude sexual sexually explicit literature poem poetry erotic writing fic fanfic fiction porn smut lemon lime slash ship shipping het shota loli lolli one shot one-shot oneshot futa",question:"You prohibit the submission of 'pornographic literature'; what do you consider this to be?"},
{id:305,keywords:"nudity nude sex sexual adult mature censor porn censored yaoi yiff homosexual relations intimate 18 futa slash het hetero ship shipping lemon lime porn shota pedo blur pixel hentai oneshot one-shot fic fiction comic loli lolli",question:"Is posting 'Adult' oriented artwork alright if I censor it first?"},
{id:565,keywords:"sex masturbation breasts boob penis nude naked erection penis pussy vagina porn cock porno pornography dick tits pedo ship shipping slash het hetero shota loli lolli futa",question:"You prohibit the submission of 'pornographic imagery'; what do you consider this to be?"},
{category:"Policies: Miscellaneous Policies", catpath:"deviantart/policies/miscellaneouspolicies"},
{id:73,keywords:"collection fav title folder",question:"Are there any rules for Collection folder titles?"},
{id:302,keywords:"close ban delete problem warn admin porn copyright theft steal",question:"How does the staff decide to take action? Why does it seem inconsistent?"},
{id:502,keywords:"doll maker template character generator character",question:"Can I submit things which I made using different 'games' like a doll maker or with other character generators?"},
{id:557,keywords:"doll maker template character base template",question:"Can I submit art which I have made using a 'base' (or line art) created by someone else?"},
{id:572,keywords:"fan art",question:"What does deviantART consider 'Fan Art' to be?"},
{category:"My Account: My Earnings", catpath:"deviantart/myaccount/myearnings"},
{id:97,keywords:"pricing  payment  money profit earnings",question:"How can I see how much money I've made?"},
{id:98,keywords:"pricing  payment  money profit earnings",question:"Can I cancel a check after it has already been processed?"},
{id:99,keywords:"pricing  payment  money profit earnings",question:"What should I do if I never received the check I requested from My Earnings?"},
{id:123,keywords:"pricing  payment  money profit earnings",question:"When will I receive my earnings check?"},
{category:"My Account: My Favourites & Collections", catpath:"deviantart/myaccount/myfavouritescollections"},
{id:6,keywords:"collection collections management favourite favourites favorite favorites",question:"What is the Collections Feature and how do I use it?"},
{id:244,keywords:"favourites favorites favorite favourite remove delete notified informed told message",question:"If I remove a favourite or collection, is the deviant notified of its removal?"},
{id:787,keywords:"favourites fav faves favorites sort ",question:"Can I change the order of my Favourites or select what shows up in the Favourites section?"},
{category:"My Account: My Gallery", catpath:"deviantart/myaccount/mygallery"},
{id:560,keywords:"Literature Author Tag",question:"How do I add a Literature Author tag to appear with my literature deviations? How can I remove this tag later?"},
{id:762,keywords:"folder gallery create CSS gallery style edit folder create move description icon customize",question:"What is the Gallery Folders Feature and how do I use it?"},
{id:864,keywords:"feature featured gallery section move missing browse all",question:"How can I add or remove deviations from my Featured Gallery section."},
{id:867,keywords:"move pages gallery galleries",question:"Is it possible to move deviations from one page to another in my gallery?"},
{category:"My Account: My Message Centre", catpath:"deviantart/myaccount/mymessagecentre"},
{id:1,keywords:"notes message messages comment comments notices contests replies activity feedback folder folders thumb thumbnail",question:"What is the Message Centre and how do I use it?"},
{id:37,keywords:"delete message messages centre return problem error",question:"I deleted items in my Message Centre and they all came back, why is this?"},
{id:71,keywords:"message center messages limit restriction expire time centre",question:"How long do messages stay in my Message Centre?"},
{id:87,keywords:"message center messages limit limitation restriction",question:"Is there a limit on how many messages I can have?"},
{category:"My Account: My Profile Page", catpath:"deviantart/myaccount/myprofilepage"},
{id:90,keywords:"customize profile userpage widget deviantID featured deviation deviant id newest favourite premium membership friend visitor recent  news wishlist  twitter donation donate pool commission",question:"How do I customize my profile page?"},
{id:96,keywords:"block stop people members commenting comment favorite favourite favorites favourites collection collected prevent harass harassment spam annoying rude interaction communication bully bullying",question:"Can I block people from interacting with me?"},
{id:569,keywords:"button subscribe subscribe premium gift give donate points badge brush",question:"What is the 'Give' button on profile pages for?"},
{id:896,keywords:"llama, badges",question:"People keep sending me llamas, what are they?"},
{id:897,keywords:"llama, cake, badges, block",question:"Can I turn off the ability to receive badges?"},
{category:"Policies: Nudity & Mature Content", catpath:"deviantart/policies/nuditymaturecontent"},
{id:23,keywords:"nude naked policy child underage fanfic fanart teen teenage minor smut porn erotic sex sexual pedo lemon lime boobs fic ship shipping slash het au shota loli lolli one shot one-shot oneshot futa boobs boobies penis butt ass tits nipple nipples model fic photograph drawing art comic",question:"What are deviantART's policies on nudity?"},
{id:248,keywords:"nude naked policy child underage fanfic fanart teen teenage minor smut porn erotic sex sexual pedo lemon lime boobs fic ship shipping slash het au shota loli lolli one shot one-shot oneshot futa",question:"Are there restrictions on art using children or teenagers (fictional or otherwise)?"},
{id:249,keywords:"nud naked policy photo naked child teen",question:"Are there restrictions on photographs of teenagers or children?"},
{id:252,keywords:"model release form nudity nude photograph woman man naked permission policy where find submit protection what is the",question:"Model release forms? Do I need it? What is it?"},
{category:"Policies: Ownership Issues", catpath:"deviantart/policies/ownershipissues"},
{id:5,keywords:"off site off-site emoticon emoticons smilies permission",question:"Can I use the deviantART emoticons on my website?"},
{id:94,keywords:"art use permission",question:"Can I use the works which I find on deviantART?"},
{id:226,keywords:"art own submission agreement",question:"Does deviantART own my art?"},
{category:"Policies: Permission Issues", catpath:"deviantart/policies/permissionissues"},
{id:157,keywords:"permission use stock resource resources credit crediting copyright submission deviation",question:"Can I use things created by other people in my submissions?"},
{id:193,keywords:"permission copyright owner third party use give violation policy proof license stock resource resources",question:"How do I prove that I had permission to use someone's work?"},
{id:257,keywords:"permission copyright owner third party use give violation policy proof license stock resources",question:"What sort of permission do I need to use someone else's work?"},
{id:304,keywords:"copied, traced, stole tracing theft, steal taken, character, anime, permission, copyright, copy, same, identical, my",question:"Do you remove copies and trace-over art?"},
{id:306,keywords:"credit use delete ban banned censor removed work picture image submission deviation scrap scrapbook policy rules permission stock resource resources",question:"Does 'Crediting' let me use whatever I want?"},
{category:"Policies", catpath:"deviantart/policies"},
{id:2,keywords:"theft plagiarism copyright policy use dmca digital millennium infringe steal stealing copy trace ",question:"Where can I find the official deviantART Copyright Policy?"},
{id:20,keywords:"terms service",question:"Where can I find the deviantART Terms of Service?"},
{id:33,keywords:"submission agreement rules",question:"Where can I find the deviantART Submission Agreement?"},
{id:35,keywords:"deviantART policy policies etiquette",question:"Where is the Etiquette policy for deviantART?"},
{id:76,keywords:"privacy policy",question:"Where can I find the deviantART Privacy Policy?"},
{id:220,keywords:"mature tag nude nudity blood gore violence violent",question:"What is Mature Content?"},
{id:250,keywords:"law country United States U.S. US",question:"The laws of my country differ from those of the United States- which ones apply?"},
{id:696,keywords:"Coppa child online protection act privacy account open minimum child children underage under age",question:"How does deviantART comply with COPPA?"},
{category:"Policies", catpath:"deviantfilm/policies"},
{id:47,keywords:"film copyright images logo designs music",question:"My film has some copyrighted images in it, can I still post it?"},
{id:844,keywords:"film films copyright copyrights",question:"Can I submit a film with copyrighted music?"},
{category:"Chat Network & Forums: Policy", catpath:"deviantart/chatnetworkforums/policy"},
{id:287,keywords:"rules, policy, damn, chat, unofficial, official",question:"What rules apply to the Chat Network?"},
{id:506,keywords:"forum thread comment talk praise sex explicit penis masturbate erotic chat roleplay rp role",question:"Does deviantART allow sexual discussions in comments, chatrooms or the forums?"},
{id:558,keywords:"Am I allowed to put my bot in an official channel?",question:"Am I allowed to put my bot in an Official channel?"},
{id:708,keywords:"violate close closure policy needs to be closed lock locked report forum thread forums",question:"I found a forum thread that I believe violates policies, where can I go to report it?"},
{id:795,keywords:"operate bot dAmn bots chat ",question:"Am I allowed to own a bot on the chat network?"},
{id:801,keywords:"English German Spanish Italian Forum languages thread closed forums rules policies policy post mosaic avatar plz",question:"Are there any rules for the Forums?"},
{category:"Portfolio", catpath:"premiummembership/portfolio"},
{id:103,keywords:"portfolio domain register registrar host hosting service",question:"Does my premium membership include a domain name for my portfolio?"},
{id:107,keywords:"godaddy register portfolio point domain hosting service ",question:"GoDaddy"},
{id:108,keywords:"register.com dot com register portfolio point domain hosting service ",question:"Register.com"},
{id:109,keywords:"network solutions register portfolio point domain hosting service ",question:"Network Solutions"},
{id:110,keywords:"enom dot com register portfolio point domain hosting service ",question:"Enom"},
{category:"Premium Content Platform", catpath:"premiumcontentplatform/premiumcontentplatform"},
{id:360,keywords:"premium content platform, premium content",question:"What is the Premium Content Platform?"},
{id:361,keywords:"premium content platform, premium content, purchase, buy",question:"How do I purchase Digital Files on the Premium Content Platform?"},
{id:362,keywords:"premium content platform, premium content, sell",question:"How do I sell Digital Files of art-related Content?"},
{id:363,keywords:"premium content platform, premium content, earnings, paid",question:"When do I get paid for my Digital Files of art-related content?"},
{id:364,keywords:"premium content platform, premium content, dispute",question:"How do I settle a dispute?"},
{id:365,keywords:"stock premium content platform sell",question:"May I Sell Stock on the Premium Content Platform?"},
{id:366,keywords:"mature content premium content platform sell",question:"Can I Sell Mature Content on the Premium Content Platform?"},
{id:903,keywords:"premium content platform, premium content",question:"Why may I only purchase digital content with Points?"},
{id:909,keywords:"Paypal earnings withdraw verified verify email",question:"What does a 'PayPal verified email' mean?"},
{category:"Pricing and Payment", catpath:"printsservice/pricingandpayment"},
{id:120,keywords:"pricing  payment buying selling buy sell money credit card paypal ",question:"Can I get a free sample?"},
{id:121,keywords:"pricing  payment buying selling buy sell money credit card paypal base cost basic",question:"What does it cost me to buy my own prints?"},
{id:124,keywords:"pricing payment buying selling buy sell money credit card paypal profit Premium",question:"How much of each sale do I get?"},
{id:337,keywords:"price size print product basic standard premium share profit",question:"What are the prices on prints and other products?"},
{category:"Print Approval", catpath:"printsservice/printapproval"},
{id:139,keywords:"print approval print approved approve getting",question:"I deleted the deviation and the associated print disappeared. What happened?"},
{id:140,keywords:"print approval print approved approve getting",question:"If I am updating an already approved print, why do I need to go through the approval process again?"},
{id:142,keywords:"print approval print approved approve getting",question:"My image meets the requirements for a print, why was it rejected?"},
{id:143,keywords:"print approval print approved approve getting",question:"What are the requirements for a print to be approved?"},
{id:144,keywords:"print approval print approved approve getting",question:"How long does it take for my print to be approved?"},
{id:145,keywords:"print approval print approved approve getting",question:"Does the image file I submit to deviantART have to be the same file I submit to Prints?"},
{id:204,keywords:"stock rights approval permissions legal illegal copyright ",question:"If my print contains an image that isn't mine, can I still use it for print?"},
{id:706,keywords:"preview",question:"Why does my print not display the preview image I have specified in my submission?"},
{id:750,keywords:"permission collab legal copyright",question:"Is permission needed when using collaborative artwork for commercial sales?"},
{id:807,keywords:"model release form nudity nude photograph portrait people woman man naked permission policy protection",question:"Do I have to provide a Model Release to sell a print?"},
{id:882,keywords:"print quality review inspection",question:"Why do print submissions have to undergo quality control?"},
{category:"Print Image Specifications & Requirements", catpath:"printsservice/qualityresolutionaspectratioanddpi"},
{id:126,keywords:"Quality Resolution Aspect Ratio DPI pixel dots per inch pixelation",question:"What size prints are available?"},
{id:127,keywords:"Quality Resolution Aspect Ratio DPI pixel dots per inch pixelation",question:"Can I add blank space to make my products the right size?"},
{id:128,keywords:"quality Resolution Aspect Ratio DPI pixel dots per inch pixelation",question:"Why can I not resize the image to the correct DPI?"},
{id:129,keywords:"Quality Resolution Aspect Ratio DPI pixel dots per inch pixelation",question:"My piece is not the resolution or DPI you recommend. Can I still sell it?"},
{id:130,keywords:"Quality Resolution Aspect Ratio DPI pixel dots per inch pixelation",question:"Is any image with any resolution or aspect ratio printable?"},
{id:131,keywords:"Quality Resolution Aspect Ratio DPI pixel dots per inch pixelation",question:"Do I have to submit an image at a ratio that exactly matches a print size currently offered by Prints?"},
{id:132,keywords:"Quality Resolution Aspect Ratio DPI pixel dots per inch pixelation mugs mug mousepads mousepad pad pads coaster coasters products products magnet postcard canvas size minimum resolution",question:"What are the minimum image sizes for each product?"},
{id:134,keywords:"Quality Resolution Aspect Ratio DPI pixel dots per inch pixelation",question:"What does resolution mean?"},
{id:150,keywords:"Quality Resolution Aspect Ratio DPI pixel dots per inch pixelation",question:"I'm not sure if my image quality is OK. How can I tell?"},
{id:152,keywords:"Quality Resolution Aspect Ratio DPI pixel dots per inch pixelation PPI",question:"What is DPI?"},
{id:153,keywords:"Quality Resolution Aspect Ratio DPI pixel dots per inch pixelation",question:"What is aspect ratio?"},
{id:298,keywords:"products prints canvas bleed edge margin wrap mount matte border",question:"What is a bleed edge and how do I use it when preparing my artwork for printing?"},
{id:576,keywords:"template aspect ratio DPI dots per inch quality resolution psd jpg bleed wrap mount margin size products",question:"Where can I find templates to help me size my images correctly for prints?"},
{id:702,keywords:"landscape portrait orientation",question:"What do Landscape and Portrait orientation mean?"},
{category:"Deviations & Scraps: Problems & Errors", catpath:"deviantart/deviationsscraps/problemserrors"},
{id:39,keywords:"file type restrictions gallery category allow accept format rar zip 7z cur dmg ico gif swf",question:"I just tried to submit a file to X Category, but it told me the filetype I am trying to upload is not allowed. What can I do?"},
{id:49,keywords:"orientation rotated rotation upside down sideways backwards exif metadata",question:"Why is my image rotated when I upload it?"},
{id:78,keywords:"deviation deviation tier category unknown",question:"Where do I submit to if I'm not sure?"},
{id:111,keywords:"download download count statistic",question:"Why is the download count not incrementing on my deviation(s)?"},
{id:161,keywords:"frequent frequently used submitted",question:"I've submitted over X amount of deviations to a single category, but I am not presented with the option to submit to a frequently used category. Why is this?"},
{id:208,keywords:"category new add gallery subcategory subgallery request ask suggest recommend",question:"Can I suggest new submission categories to be added?"},
{id:669,keywords:"mature content logged out",question:"Why can I only see mature content submitted by myself and others while I am logged in?"},
{id:670,keywords:"tag mature content",question:"How come I cannot turn off the Mature Content option on my deviations that are submitted to the Artistic Nude and Fetish Photography sections?"},
{id:754,keywords:"download deviation scrap i do not want don't ",question:"I do not want others downloading my deviations, how do I disable this option?"},
{id:783,keywords:"original size resolution dimension altered deviation scrap",question:"I submitted a deviation or scrap and deviantART did not keep my images original dimensions. Why is this?"},
{id:788,keywords:"color colors color profile embed blurry problem error problems errors pixelated colorspace rgb",question:"I submitted an image to deviantART but the colors look different then they did on my computer or the image looks blurry or pixelated. Why is this?"},
{category:"My Account: Problems & Errors", catpath:"deviantart/myaccount/problemserrors"},
{id:105,keywords:"avatar update avatars gif problem problems lit tag website button",question:"I just uploaded or reset an Avatar, or Lit Tag, and deviantART keeps displaying the old one. Why?"},
{id:114,keywords:"password recover lost pass word",question:"I forgot my password and need it emailed to me. Where can I do this?"},
{id:641,keywords:"block 20 more than stop comment commenting visiting viewing",question:"I need to block more than 500 people from my User Page. Is this possible?"},
{id:660,keywords:"hack hacked account trouble malicious stolen password emergency",question:"My deviantART account has been hacked. What can I do?"},
{category:"Problems & Errors", catpath:"orderingsupport/problemserrors"},
{id:721,keywords:"hold authorization failed rejected declined deviant art deviantart take my money fraud decline duplicate",question:"I see a charge on my credit card even though I was told that my order failed. Did deviantART take my money?"},
{id:733,keywords:"fraudulently fraud deviant deviantart problem error not authorized charge",question:"I suspect my card has been used by someone on deviantART fraudulently. What can I do?"},
{id:734,keywords:"fraud rejected report transaction purchase order credit creditors",question:"If my credit card is rejected, will you alert any creditors?"},
{id:735,keywords:"previous subscribe credit card work fine before prior order purchase purchases",question:"Why did my credit card work fine on deviantART before, but not now?"},
{id:736,keywords:"decline declined rejected credit card order error problem",question:"Why was my credit card declined when I am able to use it fine elsewhere?"},
{id:737,keywords:"fail high risk country rejected fraud credit card purchase purchasing order ordering problem error",question:"Why did my order fail due to connecting from a High Risk location?"},
{id:870,keywords:"order trouble placing an orders",question:"I'm having trouble placing an order. Who should I contact?"},
{category:"Problems & Errors", catpath:"premiummembership/problemserrors"},
{id:48,keywords:"refund mistake",question:"I have made an error while purchasing a Premium Membership, can I get a refund?"},
{id:65,keywords:"subscription subbie sub expire expired ran out",question:"What will happen to my features once my Premium Membership expires?"},
{id:533,keywords:"refunds, adcast, subscriptions, refund premium",question:"I've changed my mind about my purchase and would like a refund, can I have one?"},
{id:617,keywords:"choice membership free account verify login error signup",question:"During sign up I accidentally selected the 'Paid' membership by mistake. Is there a way to cancel this?"},
{id:748,keywords:"not notify notified subscription email",question:"I received a Premium Membership but did not receive notification of who it was from. Why?"},
{id:785,keywords:"subscription sub active activation not premium",question:"I paid for a Premium Membership and it said my Premium Membership is activated but I do not have all my features yet. Why is this?"},
{id:823,keywords:"billing subscription premium package un-subscribe cancel automatic",question:"I selected a Billing Premium Membership Package, but decided I do not want my subscription to auto renew after all. Can I cancel my package?"},
{category:"Problems & Errors", catpath:"deviantfilm/problemserrors"},
{id:43,keywords:"submit cannot film activate privileges ",question:"I've already been accepted to submit film on deviantART and still can't submit film files, can you tell me why?"},
{id:837,keywords:"problems errors error problem film films  ",question:"My film won't load. What's the problem?"},
{id:840,keywords:"flash film films submit submission submitting",question:"If my film was made in Flash, can I still upload it?"},
{id:846,keywords:"film removed relocated",question:"My film was removed from the gallery. Why?"},
{id:856,keywords:"problems errors change film edit deviation",question:"Why can't I change my film file when I edit the deviation?"},
{id:908,keywords:"sta.sh submit film fail",question:"My film does not submit through sta.sh, it repeatedly fails, what can I do?"},
{category:"About deviantART: Promoting", catpath:"deviantart/aboutdeviantart/promoting"},
{id:21,keywords:"source mascot logo deviantART design vector raster fella user symbol deviant",question:"Where can I obtain the source files for the deviantART Mascot, Logo, and User Symbols?"},
{id:213,keywords:"buttons link linking 88x31 banner",question:"Where are the buttons for linking to deviantART?"},
{category:"Policies: Proper Submitting", catpath:"deviantart/policies/propersubmitting"},
{id:578,keywords:"screenshot still desk top removed deleted ban art desktop video game ",question:"What does deviantART consider to be a proper desktop screenshot?"},
{id:634,keywords:"deviation relocate relocated moved move to ",question:"Why was my deviation relocated or moved?"},
{id:809,keywords:"stock removed requirements moved resources",question:"What are deviantART's stock image guidelines?"},
{id:818,keywords:"wallpaper removed policy",question:"My wallpaper was removed, can you tell me why?"},
{category:"Policies: Reporting Abuse", catpath:"deviantart/policies/reportingabuse"},
{id:155,keywords:"report rip theft stolen thief copyright infringe steal",question:"How do I report a deviation which I think breaks the rules?"},
{id:238,keywords:"report harass abuse bully bullying",question:"How do I report people for abuse, harassment, or another issue I think is a problem?"},
{category:"Deviations & Scraps: Scraps", catpath:"deviantart/deviationsscraps/scraps"},
{id:242,keywords:"scraps scrapbook locate browse",question:"What are scraps?"},
{id:243,keywords:"convert scrap scraps scrapbook make change",question:"How do I change an already submitted deviation to a scrap and vice versa?"},
{category:"Search", catpath:"deviantart/search"},
{id:535,keywords:"random, deviation, deviant, search, group",question:"Can I search for a random Deviant/Deviation?"},
{id:577,keywords:"search deviant user username specific find",question:"How do I use the Search?"},
{category:"Selling Prints", catpath:"printsservice/sellingprints"},
{id:122,keywords:"pricing  payment buying selling buy sell money credit card paypal ",question:"Is there a maximum/minimum selling price?"},
{id:178,keywords:"selling sell sells sold advertising advertise pay paid",question:"How do I know if my print is selling ?"},
{id:261,keywords:"print digital content edit add delete pcp premium content platform commissions",question:"Where can I view earnings reports and statistics on my Prints, digital content, and Commissions?"},
{id:309,keywords:"stats, sold",question:"Why do my stats not reflect an order which I know I sold?"},
{id:613,keywords:"sell prints age 18 minimum age minor",question:"How old do I have to be to sell my prints?"},
{id:640,keywords:"Prints Profits Tax taxes ",question:"Are we obliged to declare our prints profits as taxable income?"},
{id:862,keywords:"pricing prints sales advertising",question:"Can I use my deviantART Print account to advertise other print stores?"},
{category:"Problems & Errors: Server Issues", catpath:"deviantart/problemserrors/serverissues"},
{id:190,keywords:"deviation display submit gallery recent lag favourite",question:"I submitted data to deviantART, but it did not post. Why?"},
{id:505,keywords:"read-only read only system maintenance login ",question:"What does Read-Only Mode mean?"},
{id:701,keywords:"chat damn read-only read only",question:"How come I can still chat on dAMN while in read-only mode, but cannot open a new connection to it?"},
{category:"Shipping", catpath:"printsservice/shipping"},
{id:118,keywords:"Shipping mail locations costs shipment shipments",question:"What are the shipping charges?"},
{id:119,keywords:"Shipping mail locations costs shipment shipments countries country where place",question:"Where can prints be shipped?"},
{id:172,keywords:"shipping cost ship mail print package arrive prints when will my prints get here post fedex arrival delivery postal",question:"How long does it take to receive my order?"},
{id:344,keywords:"FedEX, USPS, shipping, options, option, ship, delivery, mail",question:"What methods are available for shipping?"},
{id:345,keywords:"shipping address view security ship prints wishlist ",question:"Will other deviants be able to see my shipping address after I add it to my wishlist?"},
{id:498,keywords:"long order shipped processing process",question:"How long will it take for my order to be shipped?"},
{id:545,keywords:"FedEx PO BOX shipping prints po boxes address post postage posting apo fpo APO FPO military army armed services",question:"Can FedEx ship to Post Office Boxes or APO/FPO military addresses?"},
{id:636,keywords:"customs, taxes, delivery, international, foreign, tax, shipping, ship, delivery, custom, import, charges",question:"Are there any taxes or charges applied to packages once they cross the border?"},
{id:695,keywords:"Shipping mail locations shipment shipments order lost damage guarantee fedex usps order refund return returns shipping ship parcel",question:"What happens if my order does not arrive or arrives damaged?"},
{id:726,keywords:"missing, separate, shipping, package, processing time, miss",question:"My order arrived but I am missing some items, were they shipped separately?"},
{id:727,keywords:"package packaging box ship shipping delivery damage envelope",question:"How are prints packaged?"},
{category:"About deviantART: Staff", catpath:"deviantart/aboutdeviantart/staff"},
{id:25,keywords:"admin staff deviantART",question:"Can I be a deviantART administrator?"},
{id:84,keywords:"core values volunteer community relations CR",question:"What are the Core Values of the Community Relations Department?"},
{id:85,keywords:"volunteer deviantart can how community relations operations",question:"Can I be a volunteer on deviantART?"},
{id:324,keywords:"staff merits merit members symbols icons status",question:"What do the Staff Merit Badges stand for?"},
{id:504,keywords:"staff list admin administrators admins about",question:"Is there an official staff listing?"},
{category:"Stash", catpath:"deviantart/stash"},
{id:440,keywords:"stash sta.sh sta sh submit publish",question:"What is Sta.sh?"},
{id:441,keywords:"stash sta.sh sta sh submit publish ftp file transfer protocol mail email e-mail api",question:"How do I upload to my Sta.sh?"},
{id:442,keywords:"stash sta.sh sta sh submit publish",question:"What is the storage limit of Sta.sh?"},
{id:443,keywords:"stash sta.sh sta sh storage limit",question:"What happens when I reach the storage limit for Sta.sh?"},
{id:444,keywords:"stash sta.sh sta sh subscription premium ",question:"What happens to my Sta.sh items when my subscription runs out?"},
{id:445,keywords:"stash sta.sh sta sh submit publish content allowed rules",question:"Can I upload anything to Sta.sh?"},
{id:446,keywords:"stash sta.sh sta sh submit publish drag drop browser",question:"Why can't I drag & drop files to my Sta.sh like other users?"},
{category:"My Account: Statistics", catpath:"deviantart/myaccount/statistics"},
{id:164,keywords:"statistics profile bar age sex location tagline daily pageviews name recent activity private deviant type hide online status pageviews subscribed premium",question:"What is my profile bar and how do I use it?"},
{id:499,keywords:"gallery, stats, statistics, gallery stats, gallery statistics",question:"What are Gallery Stats, and how can I view them?"},
{id:714,keywords:"gallery stats details boxes stat color",question:"What does the color of the Gallery Stats boxes mean?"},
{id:715,keywords:"stats gallery stat boxes size",question:"What does the size of the Gallery Stats boxes mean?"},
{category:"Deviations & Scraps: Stock", catpath:"deviantart/deviationsscraps/stock"},
{id:217,keywords:"stock photo photos what photography resource resources credit submission crediting",question:"What are 'Stock and Resources' and can I use them in my submissions?"},
{category:"Store and Product Management", catpath:"printsservice/storeandproductmanagement"},
{id:622,keywords:"print digital content edit add delete pcp premium content platform",question:"How do I add, edit, or delete my Prints or digital content?"},
{id:623,keywords:"store storefront information awards education biography contact featured products account",question:"How can I modify the appearance and information of my artist store?"},
{id:624,keywords:"prints print help customer service representative inquiry account weekends close open business hours time holidays",question:"I need help with Prints from a real person! Where can I get it?"},
{id:793,keywords:"request stat",question:"Where can I see how often a deviation of mine has been requested as a Print?"},
{category:"Deviations & Scraps: Submitting", catpath:"deviantart/deviationsscraps/submitting"},
{id:79,keywords:"deviations deviation submit upload keywords details submission submitting gallery description title add art pic photo lit literature",question:"How do I submit art?"},
{id:816,keywords:"wallpaper brush brushes zip rar",question:"How do I upload a collection of images or files, such as brushes, wallpapers or other?"},
{category:"Submitting Products", catpath:"printsservice/submittingproducts"},
{id:146,keywords:"print approval print approved approve getting",question:"Do I have to submit an image to deviantART before submitting an image to Prints?"},
{id:149,keywords:"I can't upload my file Are there any punctuation limitations on filenames",question:"I can't upload my file. Are there any punctuation limitations on filenames?"},
{id:151,keywords:"Quality Resolution Aspect Ratio DPI pixel dots per inch pixelation",question:"Will I be able to get prints made of my desktop wallpaper?"},
{id:154,keywords:"print approval print approved approve getting ftp",question:"Why isn't my source file uploading correctly?"},
{id:182,keywords:"",question:"Why do I need a source file?"},
{id:285,keywords:"edit update print upload renew change fix repair revise alter modify crop trim adjust scale matte border",question:"How do I edit an existing print or add more product options to a print?"},
{id:297,keywords:"upload ftp submission",question:"When I upload images using FTP, they do not show up in the File Deck."},
{id:559,keywords:"guide help submit submission product design layout tutorial advise",question:"Are there any guides to aide in the submission of my prints?"},
{id:616,keywords:"existing deviation as print print upload add",question:"How can I submit an existing deviation as a print?"},
{id:620,keywords:"submit submission print product detail guide help upload image picture watermark source crop trim adjust scale matte border size price sell sale finish",question:"How do I submit print products?"},
{id:677,keywords:"ftp upload transfer submit submission file transfer protocol",question:"How do I upload my prints using FTP?"},
{id:698,keywords:"calendar design, month, date, year, product, guide",question:"How should I design and submit a calendar?"},
{id:712,keywords:"file size limit prints source image large limitation premium standard ftp file deck",question:"Are there any limitations on file upload and the storage of print files?"},
{id:877,keywords:"print adjust change edit upload crop cut trim fit scale matte border color select portion resize source image rgb hex orientation landscape portrait guide how walkthrough advise",question:"How do I use the Adjust Image tool?"},
{id:881,keywords:"submit Create New Print deck edit existing",question:"Why does 'Submit Print Step 1 - Select Deviation' not display all of my deviations?"},
{id:890,keywords:"cancel abort not no submit sell print product disable",question:"What do I have to do to not submit a print after submitting a new deviation?"},
{category:"Submitting Questions", catpath:"deviantfilm/submittingquestions"},
{id:832,keywords:"file formats film submission films submit accepted",question:"What file formats are accepted for film?"},
{id:834,keywords:"film films submission submit frame rate size submissions",question:"What screen size and frame rate should I use for my film submissions?"},
{id:835,keywords:"film films submission submitting submit parts part chapters",question:"If I have a film that is longer than 20 minutes or larger than 200 MB. Can I submit it in to two parts?"},
{id:842,keywords:"member become submitting submission film community submit apply application",question:"How do I become a submitting member of the film community?"},
{id:843,keywords:"fan film films ",question:"What is a fan film?"},
{id:845,keywords:"fan film submit submission submitting ",question:"Can I submit a Fan Film?"},
{id:906,keywords:"thumbnail change film preview",question:"Can I change the thumbnail images attached to the film?"},
{id:907,keywords:"edit films ",question:"Can I edit my films on deviantART?"},
{category:"About deviantART: Suggestions", catpath:"deviantart/aboutdeviantart/suggestions"},
{id:798,keywords:"suggest suggestion deviantART deviant art",question:"I think something is missing from deviantART. Where can I go to make my suggestion?"},
{category:"Policies: Unacceptable Content", catpath:"deviantart/policies/unacceptablecontent"},
{id:7,keywords:"animal cruelty death corpse dead",question:"What is the policy concerning photographs of corpses, cruelty or death?"},
{id:12,keywords:"hate",question:"deviantART doesn't allow 'Hate Art', 'Hate Speech' or 'Hate Propaganda', what is this?"},
{id:60,keywords:"sex masturbation breasts boob penis nude naked erection penis pussy vagina porn link linking futa porn slash pedo shota lemon lime het ship shipping loli lolli censor shota pedo fic oneshot one-shot uncensored",question:"Do you allow 'Adult', explicit sexual or pornographic content on deviantART? How about linking off site?"},
{id:165,keywords:"shit crap feces waste toilet vomit pee piss urine semen poo poop fecal",question:"Do you allow images depicting bodily wastes or fluids?"},
{id:284,keywords:"cutting, harm, mutilation, injury",question:"Can we submit photographs showing actual injury, self-harm and mutilation?"},
{category:"Upgrade to a Super Group", catpath:"groups/upgradetoasupergroup"},
{id:413,keywords:"group club groups super upgrade",question:"What's a Super Group and how can I upgrade?"},
{id:433,keywords:"groups group club super cost",question:"How much is a Super Group?"},
{id:434,keywords:"groups group club super cost upgrade",question:"Who in my group is able to upgrade?"},
{id:435,keywords:"groups group club super expire",question:"What happens when my Super Group expires?"},
{category:"Viewing Questions", catpath:"deviantfilm/viewingquestions"},
{id:849,keywords:"download film films view viewing",question:"How do I download films, so I can view them later?"},
{id:851,keywords:"annotation devious add what is",question:"What is an annotation and how can I add one, or read those already added?"},
{id:857,keywords:"film scrubbing scrubber films",question:"What is 'scrubbing'?"},
{category:"Deviations & Scraps: Wallpaper", catpath:"deviantart/deviationsscraps/wallpaper"},
{id:811,keywords:"wallpaper desktop background resolution",question:"What is a Wallpaper and what should I know about using and making wallapers?"},
{id:821,keywords:"wallpaper resolution downloading",question:"How do I know what wallpaper resolution will look best on my monitor?"});
FAQloaded=true;